//HintName: ChainedEmbedInputDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ChainedEmbedInputDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType> ProcessChainedEmbedInputAsync(
		ChainedEmbedInputRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		List<TestCase.Models.Structure> __Structure = [];
		List<int> __Structure__ContactID = [];
		List<TestCase.Models.Contact> __Contact = [];
		List<int> __Contact__AddressID = [];
		var __ContactSeen = new Dictionary<int, (TestCase.Models.Contact Row, TestCase.Models.Contact Source)>();
		List<TestCase.Models.Address> __Address = [];
		var __AddressSeen = new Dictionary<int, TestCase.Models.Address>();
		
		foreach (var structure in request.Structure ?? [])
		{
			__Structure.Add(new(
				structure.Title));
			__Structure__ContactID.Add((structure.Contact ?? throw new InvalidOperationException("ChainedEmbedInputRequest Structure.Contact is required: it supplies the not-null ContactID column.")).ContactID);
			if (structure.Contact is not null)
			{
				var contact = structure.Contact;
				var __ContactRow = new TestCase.Models.Contact(
					contact.ContactID,
					contact.Name);
				if (__ContactSeen.TryGetValue(__ContactRow.ContactID, out var __ContactPrev))
				{
					if (__ContactPrev.Row.ContactID != __ContactRow.ContactID || __ContactPrev.Row.Name != __ContactRow.Name || __ContactPrev.Source.Address?.AddressID != contact.Address?.AddressID)
					{
						throw new Exception($"Conflicting values supplied for Contact with ContactID '{__ContactRow.ContactID}'.");
					}
				}
				else
				{
					__ContactSeen[__ContactRow.ContactID] = (__ContactRow, contact);
					__Contact.Add(__ContactRow);
					__Contact__AddressID.Add((contact.Address ?? throw new InvalidOperationException("ChainedEmbedInputRequest Contact.Address is required: it supplies the not-null AddressID column.")).AddressID);
					if (contact.Address is not null)
					{
						var address = contact.Address;
						var __AddressRow = new TestCase.Models.Address(
							address.AddressID,
							address.Street);
						if (__AddressSeen.TryGetValue(__AddressRow.AddressID, out var __AddressPrev))
						{
							if (__AddressPrev.AddressID != __AddressRow.AddressID || __AddressPrev.Street != __AddressRow.Street)
							{
								throw new Exception($"Conflicting values supplied for Address with AddressID '{__AddressRow.AddressID}'.");
							}
						}
						else
						{
							__AddressSeen[__AddressRow.AddressID] = __AddressRow;
							__Address.Add(__AddressRow);
						}
					}
				}
			}
		}
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(SqlException e)
		{
			return new SQuiLResultType(CreateError(e));
		}
		
		string inputStructure(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Structure)
			{
				if (item.Title is not null && item.Title.Length > 50)
				{
					throw new Exception($"ChainedEmbedInputRequest Structure[{index}].Title exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Structure", System.Linq.Enumerable.ToList(System.Linq.Enumerable.Select(__Structure, (__r, __i) => new { Title = __r.Title, ContactID = __Structure__ContactID[__i] })));
			
			return """
			Insert Into @Params_Structure([Title], [ContactID])
			Select [Title], [ContactID]
			From OpenJson(@__json_Params_Structure)
			With (
				[Title] varchar(50) '$.Title',
				[ContactID] int '$.ContactID');
			""";
		}
		
		string inputContact(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Contact)
			{
				if (item.Name is not null && item.Name.Length > 50)
				{
					throw new Exception($"ChainedEmbedInputRequest Contact[{index}].Name exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Contact", System.Linq.Enumerable.ToList(System.Linq.Enumerable.Select(__Contact, (__r, __i) => new { ContactID = __r.ContactID, Name = __r.Name, AddressID = __Contact__AddressID[__i] })));
			
			return """
			Insert Into @Params_Contact([ContactID], [Name], [AddressID])
			Select [ContactID], [Name], [AddressID]
			From OpenJson(@__json_Params_Contact)
			With (
				[ContactID] int '$.ContactID',
				[Name] varchar(50) '$.Name',
				[AddressID] int '$.AddressID');
			""";
		}
		
		string inputAddress(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Address)
			{
				if (item.Street is not null && item.Street.Length > 50)
				{
					throw new Exception($"ChainedEmbedInputRequest Address[{index}].Street exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Address", __Address);
			
			return """
			Insert Into @Params_Address([AddressID], [Street])
			Select [AddressID], [Street]
			From OpenJson(@__json_Params_Address)
			With (
				[AddressID] int '$.AddressID',
				[Street] varchar(50) '$.Street');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Structure table(
			[Title] varchar(50),
			[ContactID] int);
		{inputStructure(parameters)}
		
		Declare @Params_Contact table(
			[ContactID] int,
			[Name] varchar(50),
			[AddressID] int);
		{inputContact(parameters)}
		
		Declare @Params_Address table(
			[AddressID] int,
			[Street] varchar(50));
		{inputAddress(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Insert Into dbo.Structures Select Title, ContactID From @Params_Structure;
		Insert Into dbo.Contacts Select ContactID, Name, AddressID From @Params_Contact;
		Insert Into dbo.Addresses Select AddressID, Street From @Params_Address;
		""";
	}
}
