//HintName: TestCase.ZeroConfigDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class ZeroConfigDataContext : SqlServerDataContext
{
    public ZeroConfigDataContext(IConfiguration Configuration) : base(Configuration) { }
}
