//HintName: TransactionWithoutDebugAlwaysCommitsResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TransactionWithoutDebugAlwaysCommitsResponse
{
	public int Count { get; set; }
}
