//HintName: TestCase.TransactionWithoutDebugAlwaysCommitsDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class TransactionWithoutDebugAlwaysCommitsDataContext : SqlServerDataContext
{
    public TransactionWithoutDebugAlwaysCommitsDataContext(IConfiguration Configuration) : base(Configuration) { }
}
