//HintName: AllColumnsDefaultedResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record AllColumnsDefaultedResponse
{
	public System.Collections.Generic.List<RowsTable> Rows { get; set; } = [];
}
