//HintName: Rows.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Rows()
{
	public decimal Amount { get; init; } = 1.5m;
	public string Note { get; init; } = "hello";
}
