//HintName: EmptyNamespaceOverrideEmitsTopLevelResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record EmptyNamespaceOverrideEmitsTopLevelResponse
{
	public System.Collections.Generic.List<TestCase.Person>? Person { get; set; }
}
