//HintName: EmptyNamespaceOverrideEmitsTopLevelDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class EmptyNamespaceOverrideEmitsTopLevelDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<EmptyNamespaceOverrideEmitsTopLevelResponse>> ProcessEmptyNamespaceOverrideEmitsTopLevelAsync(
		EmptyNamespaceOverrideEmitsTopLevelRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		EmptyNamespaceOverrideEmitsTopLevelResponse response = new();
		
		var isPerson = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "personid:int|fullname:string":
					{
						isPerson = true;
						
						response.Person ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexPersonID = reader.GetOrdinal("PersonID");
						var indexFullName = reader.GetOrdinal("FullName");
						
						do
						{
							var valuePersonID = reader.GetInt32(indexPersonID);
							var valueFullName = reader.GetString(indexFullName);
							
							response.Person.Add(new(
								valuePersonID,
								valueFullName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isPerson) errors.Add(new(51001, 12, 1, 82, "Person", "Expected return table `Person`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Person table(
			[PersonID] int,
			[FullName] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
