//HintName: PrimaryKeysNoLinksInputRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record PrimaryKeysNoLinksInputRequest
{
	public System.Collections.Generic.List<TestCase.Models.Alpha>? Alpha { get; set; } = [];
	
	public System.Collections.Generic.List<TestCase.Models.Beta>? Beta { get; set; } = [];
}
