//HintName: PrimaryKeysNoLinksInputDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class PrimaryKeysNoLinksInputDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessPrimaryKeysNoLinksInputAsync(
		PrimaryKeysNoLinksInputRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputAlpha(List<DbParameter> parameters)
		{
			if (request.Alpha is null || request.Alpha.Count == 0) return "";
			
			AddJsonParameter(parameters, "@__json_Params_Alpha", request.Alpha);
			
			return """
			Insert Into @Params_Alpha([AlphaID], [N])
			Select [AlphaID], [N]
			From OpenJson(@__json_Params_Alpha)
			With (
				[AlphaID] int '$.AlphaID',
				[N] int '$.N');
			""";
		}
		
		string inputBeta(List<DbParameter> parameters)
		{
			if (request.Beta is null || request.Beta.Count == 0) return "";
			
			AddJsonParameter(parameters, "@__json_Params_Beta", request.Beta);
			
			return """
			Insert Into @Params_Beta([BetaID], [M])
			Select [BetaID], [M]
			From OpenJson(@__json_Params_Beta)
			With (
				[BetaID] int '$.BetaID',
				[M] int '$.M');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Alpha table(
			[AlphaID] int,
			[N] int);
		{inputAlpha(parameters)}
		
		Declare @Params_Beta table(
			[BetaID] int,
			[M] int);
		{inputBeta(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Insert Into dbo.Alphas Select AlphaID, N From @Params_Alpha;
		Insert Into dbo.Betas Select BetaID, M From @Params_Beta;
		""";
	}
}
