//HintName: ColumnDefaultsTrailingRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ColumnDefaultsTrailingRequest
{
	public System.Collections.Generic.List<Rows>? Rows { get; set; } = [];
}
