//HintName: ColumnDefaultsTrailingDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ColumnDefaultsTrailingDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessColumnDefaultsTrailingAsync(
		ColumnDefaultsTrailingRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputRows(List<DbParameter> parameters)
		{
			if (request.Rows is null || request.Rows.Count == 0) return "";
			
			var index = 0;
			foreach (var item in request.Rows)
			{
				if (item.Note is not null && item.Note.Length > 50)
				{
					throw new Exception($"ColumnDefaultsTrailingRequest Rows[{index}].Note exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Rows", request.Rows);
			
			return """
			Insert Into @Params_Rows([RowID], [Amount], [Note])
			Select [RowID], [Amount], [Note]
			From OpenJson(@__json_Params_Rows)
			With (
				[RowID] int '$.RowID',
				[Amount] decimal(18,2) '$.Amount',
				[Note] varchar(50) '$.Note');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Rows table(
			[RowID] int,
			[Amount] decimal(18,2),
			[Note] varchar(50));
		{inputRows(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
