//HintName: BigintKeyInputNestingRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record BigintKeyInputNestingRequest
{
	public TestCase.Models.Order? Order { get; set; } = default!;
}
