//HintName: DebugRollbackHoistsDebugAndGatesCommitRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DebugRollbackHoistsDebugAndGatesCommitRequest
{
	public bool Debug { get; set; }
}
