//HintName: DebugRollbackHoistsDebugAndGatesCommitResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DebugRollbackHoistsDebugAndGatesCommitResponse
{
	public int Count { get; set; }
}
