//HintName: TestCase.DebugRollbackHoistsDebugAndGatesCommitDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class DebugRollbackHoistsDebugAndGatesCommitDataContext : SqlServerDataContext
{
    public DebugRollbackHoistsDebugAndGatesCommitDataContext(IConfiguration Configuration) : base(Configuration) { }
}
