//HintName: TestCase.Input2VariableDataContext.Input2VariableObjectObject.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Input2VariableObjectObject(
	int ObjectID,
	bool IsMale,
	string FirstName);
