//HintName: TestCase.Input2VariableDataContext.Input2VariableRequestObjectObject.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Input2VariableRequestObjectObject(
	int ObjectID,
	bool IsMale,
	string FirstName);
