//HintName: InputTableQueryGeneratesJsonEachShredDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.Sqlite;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class InputTableQueryGeneratesJsonEachShredDataContext : SqliteDataContext
{
	public async Task<SQuiLResultType<InputTableQueryGeneratesJsonEachShredResponse>> ProcessInputTableQueryGeneratesJsonEachShredAsync(
		InputTableQueryGeneratesJsonEachShredRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		InputTableQueryGeneratesJsonEachShredResponse response = new();
		
		var isImported = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "docid:long|title:string":
					{
						isImported = true;
						
						response.Imported ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexDocID = reader.GetOrdinal("DocID");
						var indexTitle = reader.GetOrdinal("Title");
						
						do
						{
							var valueDocID = reader.GetInt64(indexDocID);
							var valueTitle = reader.GetString(indexTitle);
							
							response.Imported.Add(new(
								valueDocID,
								valueTitle));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqliteException e)
		{
			errors.Add(CreateError(e));
		}
		
		if (!isImported) errors.Add(new(51001, 12, 1, 82, "Imported", "Expected return table `Imported`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string inputDoc(List<DbParameter> parameters)
		{
			if (request.Doc is null || request.Doc.Count == 0) return "";
			
			AddJsonParameter(parameters, "@__json_Params_Doc", request.Doc);
			
			return """
			Insert Into Params_Doc([DocID], [Title], [Payload])
			Select json_extract(value, '$.DocID'), json_extract(value, '$.Title'), unhex(json_extract(value, '$.Payload'))
			From json_each(@__json_Params_Doc);
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Drop Table If Exists Params_Doc;
		Create Temp Table Params_Doc (
			DocID INTEGER Not Null Primary Key,
			Title TEXT Not Null,
			Payload BLOB Not Null);
		{inputDoc(parameters)}
		
		Drop Table If Exists Returns_Imported;
		Create Temp Table Returns_Imported (
			DocID INTEGER Not Null,
			Title TEXT Not Null);
		
		
		
		Insert Into Returns_Imported (DocID, Title) Select DocID, Title From Params_Doc;
		Select DocID, Title From Returns_Imported;
		""";
	}
}
