//HintName: InputTableQueryGeneratesJsonEachShredResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputTableQueryGeneratesJsonEachShredResponse
{
	public System.Collections.Generic.List<TestCase.Models.Imported>? Imported { get; set; }
}
