//HintName: SameNameAcrossFilesObjectDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class SameNameTableAndObjectAcrossFilesShareOneRecordDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<SameNameAcrossFilesObjectResponse>> ProcessSameNameAcrossFilesObjectAsync(
		SameNameAcrossFilesObjectRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		SameNameAcrossFilesObjectResponse response = new();
		
		var isPerson = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Return_Person__":
						{
							if (isPerson) throw new Exception(
								"Already returned value for `Person`");
							
							isPerson = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							if (response.Person is not null)
								throw new Exception("Person was already set.");
							
							if (reader.GetString(0) == "Return_Person")
							{
								response.Person = new(
									reader.GetInt32(reader.GetOrdinal("PersonID")),
									reader.GetString(reader.GetOrdinal("FullName")));
							}
							else
							{
								continue;
							}
							
							if (await reader.ReadAsync(cancellationToken))
								throw new Exception(
									"Return object results in more than one object. Consider using a return table instead.");
							
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isPerson) errors.Add(new(51001, 12, 1, 92, "Person", "Expected return object `Person`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Person table(
			[__SQuiL__Table__Type__Return_Person__] varchar(max) default('Return_Person'),
			[PersonID] int,
			[FullName] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
