//HintName: SameNameAcrossFilesObjectResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SameNameAcrossFilesObjectResponse
{
	public TestCase.Models.Person? Person { get; set; } = default!;
}
