//HintName: SameNameAcrossFilesListResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SameNameAcrossFilesListResponse
{
	public System.Collections.Generic.List<TestCase.Models.Person>? Person { get; set; }
}
