//HintName: InputTableQueryGeneratesJsonToRecordsetShredResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputTableQueryGeneratesJsonToRecordsetShredResponse
{
	public System.Collections.Generic.List<TestCase.Models.Imported>? Imported { get; set; }
}
