//HintName: InputTableQueryGeneratesJsonToRecordsetShredRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputTableQueryGeneratesJsonToRecordsetShredRequest
{
	public System.Collections.Generic.List<TestCase.Models.Person>? Person { get; set; } = [];
}
