//HintName: TranscriptProcessingRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TranscriptProcessingRequest
{
	public bool Debug { get; set; }
	
	public bool IncludeCompletedTranscripts { get; set; }
	
	public int? ReferenceID { get; set; }
	
	public System.DateTime? IssueDate { get; set; }
	
	public StudentObject? Student { get; set; } = default!;
	
	public InstitutionObject? Institution { get; set; } = default!;
	
	public System.Collections.Generic.List<CoursesTable>? Courses { get; set; } = [];
}
