//HintName: Student.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Student(
	string? ColleagueID,
	string FirstName,
	string LastName,
	string? MiddleName,
	System.DateOnly? DateOfBirth);
