//HintName: Courses.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Courses(
	string Term,
	string Code,
	string Number,
	string Title,
	string Score,
	decimal Credits);
