//HintName: TranscriptProcessingDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class TranscriptProcessingDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessTranscriptProcessingAsync(
		TranscriptProcessingRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, request.Debug || EnvironmentName != "Production"),
			CreateParameter("@Param_IncludeCompletedTranscripts", System.Data.SqlDbType.Bit, request.IncludeCompletedTranscripts),
			CreateParameter("@Param_ReferenceID", System.Data.SqlDbType.BigInt, request.ReferenceID),
			CreateParameter("@Param_IssueDate", System.Data.SqlDbType.DateTime, request.IssueDate)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputStudent(List<DbParameter> parameters)
		{
			if (request.Student is null)
				throw new NullReferenceException(
					"TranscriptProcessingRequest is missing the required property Student.");
			
			if (request.Student.ColleagueID is not null && request.Student.ColleagueID.Length > 50)
			{
				throw new Exception($"TranscriptProcessingRequest Student.ColleagueID exceeds its maximum length of 50 characters.");
			}
			if (request.Student.FirstName is not null && request.Student.FirstName.Length > 100)
			{
				throw new Exception($"TranscriptProcessingRequest Student.FirstName exceeds its maximum length of 100 characters.");
			}
			if (request.Student.LastName is not null && request.Student.LastName.Length > 100)
			{
				throw new Exception($"TranscriptProcessingRequest Student.LastName exceeds its maximum length of 100 characters.");
			}
			if (request.Student.MiddleName is not null && request.Student.MiddleName.Length > 100)
			{
				throw new Exception($"TranscriptProcessingRequest Student.MiddleName exceeds its maximum length of 100 characters.");
			}
			
			AddJsonParameter(parameters, "@__json_Param_Student", new[] { request.Student });
			
			return """
			Insert Into @Param_Student([ColleagueID], [FirstName], [LastName], [MiddleName], [DateOfBirth])
			Select [ColleagueID], [FirstName], [LastName], [MiddleName], [DateOfBirth]
			From OpenJson(@__json_Param_Student)
			With (
				[ColleagueID] varchar(50) '$.ColleagueID',
				[FirstName] varchar(100) '$.FirstName',
				[LastName] varchar(100) '$.LastName',
				[MiddleName] varchar(100) '$.MiddleName',
				[DateOfBirth] date '$.DateOfBirth');
			""";
		}
		
		string inputInstitution(List<DbParameter> parameters)
		{
			if (request.Institution is null)
				throw new NullReferenceException(
					"TranscriptProcessingRequest is missing the required property Institution.");
			
			if (request.Institution.InstitutionID is not null && request.Institution.InstitutionID.Length > 50)
			{
				throw new Exception($"TranscriptProcessingRequest Institution.InstitutionID exceeds its maximum length of 50 characters.");
			}
			if (request.Institution.SchoolName is not null && request.Institution.SchoolName.Length > 200)
			{
				throw new Exception($"TranscriptProcessingRequest Institution.SchoolName exceeds its maximum length of 200 characters.");
			}
			if (request.Institution.CEEB is not null && request.Institution.CEEB.Length > 20)
			{
				throw new Exception($"TranscriptProcessingRequest Institution.CEEB exceeds its maximum length of 20 characters.");
			}
			
			AddJsonParameter(parameters, "@__json_Param_Institution", new[] { request.Institution });
			
			return """
			Insert Into @Param_Institution([InstitutionID], [SchoolName], [CEEB])
			Select [InstitutionID], [SchoolName], [CEEB]
			From OpenJson(@__json_Param_Institution)
			With (
				[InstitutionID] varchar(50) '$.InstitutionID',
				[SchoolName] varchar(200) '$.SchoolName',
				[CEEB] varchar(20) '$.CEEB');
			""";
		}
		
		string inputCourses(List<DbParameter> parameters)
		{
			if (request.Courses is null || request.Courses.Count == 0) return "";
			
			var index = 0;
			foreach (var item in request.Courses)
			{
				if (item.Term is not null && item.Term.Length > 10)
				{
					throw new Exception($"TranscriptProcessingRequest Courses[{index}].Term exceeds its maximum length of 10 characters.");
				}
				if (item.Code is not null && item.Code.Length > 20)
				{
					throw new Exception($"TranscriptProcessingRequest Courses[{index}].Code exceeds its maximum length of 20 characters.");
				}
				if (item.Number is not null && item.Number.Length > 20)
				{
					throw new Exception($"TranscriptProcessingRequest Courses[{index}].Number exceeds its maximum length of 20 characters.");
				}
				if (item.Title is not null && item.Title.Length > 200)
				{
					throw new Exception($"TranscriptProcessingRequest Courses[{index}].Title exceeds its maximum length of 200 characters.");
				}
				if (item.Score is not null && item.Score.Length > 5)
				{
					throw new Exception($"TranscriptProcessingRequest Courses[{index}].Score exceeds its maximum length of 5 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Courses", request.Courses);
			
			return """
			Insert Into @Params_Courses([Term], [Code], [Number], [Title], [Score], [Credits])
			Select [Term], [Code], [Number], [Title], [Score], [Credits]
			From OpenJson(@__json_Params_Courses)
			With (
				[Term] varchar(10) '$.Term',
				[Code] varchar(20) '$.Code',
				[Number] varchar(20) '$.Number',
				[Title] varchar(200) '$.Title',
				[Score] varchar(5) '$.Score',
				[Credits] decimal '$.Credits');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Param_Student table(
			[__SQuiL__Table__Type__Param_Student__] varchar(max) default('Param_Student'),
			[ColleagueID] varchar(50) Null,
			[FirstName] varchar(100),
			[LastName] varchar(100),
			[MiddleName] varchar(100) Null,
			[DateOfBirth] date Null);
		{inputStudent(parameters)}
		
		Declare @Param_Institution table(
			[__SQuiL__Table__Type__Param_Institution__] varchar(max) default('Param_Institution'),
			[InstitutionID] varchar(50) Null,
			[SchoolName] varchar(200),
			[CEEB] varchar(20));
		{inputInstitution(parameters)}
		
		Declare @Params_Courses table(
			[__SQuiL__Table__Type__Params_Courses__] varchar(max) default('Params_Courses'),
			[Term] varchar(10),
			[Code] varchar(20),
			[Number] varchar(20),
			[Title] varchar(200),
			[Score] varchar(5),
			[Credits] decimal);
		{inputCourses(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Begin Transaction;
		
		Begin Try
		
			If (Select 1 From TranscriptImports Where ReferenceID = @Param_ReferenceID) = 1 Begin
		
				Update    TranscriptImports
				Set            IssueDate = @Param_IssueDate,
								ReceivedAt = SysDateTimeOffset()
				Where        ReferenceID = @Param_ReferenceID;
		
			End
			Else Begin
		
				Insert Into TranscriptImports (ReferenceID, IssueDate, ReceivedAt)
				Values (@Param_ReferenceID, @Param_IssueDate, SysDateTimeOffset());
		
			End;
		
			Update    TranscriptImports
			Set            ColleagueID = ColleagueID,
							FirstName = FirstName,
							LastName = LastName ,
							MiddleName = MiddleName ,
							DateOfBirth = DateOfBirth
			From        TranscriptImports
							Cross Join @Param_Student
			Where        ReferenceID = @Param_ReferenceID;
		
			Update    InstitutionalRecords
			Set            InstitutionID = InstitutionID ,
							SchoolName = SchoolName ,
							CEEB = CEEB
			From        TranscriptImports
							Cross Join @Param_Institution
			Where        ReferenceID = @Param_ReferenceID;
		
			Delete    From TranscriptImportCourses
			Where        ReferenceID = @Param_ReferenceID;
		
			Insert Into TranscriptImportCourses (Term, Code, Number, Title, Score, Credits, ReferenceID)
			Select Term, Code, Number, Title, Score, Credits, @Param_ReferenceID
			From        @Params_Courses
		
			If @@TRANCOUNT > 0 Begin
				If @Debug = 1 Begin
					Rollback Transaction;
				End
				Else Begin
					Commit Transaction;
				End;
			End;
		End Try
		Begin Catch
			If @@TRANCOUNT > 0 Begin
				Rollback Transaction;
			End;
		
			Throw;
		End Catch
		
		""";
	}
}
