//HintName: CaseMismatchedKeyDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

using SQuiL;

namespace TestCase;

partial class CaseMismatchedKeyDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType<CaseMismatchedKeyResponse>> ProcessCaseMismatchedKeyAsync(
		CaseMismatchedKeyRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		CaseMismatchedKeyResponse response = new();
		
		var isOrder = false;
		var isCustomer = false;
		var isLine = false;
		
		List<SQuiLError> errors = [];
		try
		{
			List<TestCase.Models.Order> __Order = [];
			List<int> __Order__CustomerId = [];
			List<TestCase.Models.Customer> __Customer = [];
			List<TestCase.Models.Line> __Line = [];
			
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "orderid:int|customerid:int":
					{
						isOrder = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexOrderID = reader.GetOrdinal("OrderID");
						var indexCustomerId = reader.GetOrdinal("CustomerId");
						
						do
						{
							var valueOrderID = reader.GetInt32(indexOrderID);
							var valueCustomerId = reader.GetInt32(indexCustomerId);
							
							__Order.Add(new(
								valueOrderID));
							__Order__CustomerId.Add(valueCustomerId);
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "customerid:int|name:string":
					{
						isCustomer = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexCustomerID = reader.GetOrdinal("CustomerID");
						var indexName = reader.GetOrdinal("Name");
						
						do
						{
							var valueCustomerID = reader.GetInt32(indexCustomerID);
							var valueName = reader.GetString(indexName);
							
							__Customer.Add(new(
								valueCustomerID,
								valueName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "lineid:int|orderid:int|sku:string":
					{
						isLine = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexLineID = reader.GetOrdinal("LineID");
						var indexOrderId = reader.GetOrdinal("OrderId");
						var indexSku = reader.GetOrdinal("Sku");
						
						do
						{
							var valueLineID = reader.GetInt32(indexLineID);
							var valueOrderId = reader.GetInt32(indexOrderId);
							var valueSku = reader.GetString(indexSku);
							
							__Line.Add(new(
								valueLineID,
								valueOrderId,
								valueSku));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
			
			for (var __i = 0; __i < __Order.Count; __i++)
			{
				var __fk = __Order__CustomerId[__i];
				var __match = __Customer.Where(c => c.CustomerID == __fk).ToList();
				if (__match.Count > 1)
				{
					throw new Exception("Lookup `Customer` has more than one row for key `CustomerID`.");
				}
				__Order[__i].Customer = __match.Count == 1 ? __match[0] : null;
			}
			foreach (var parent in __Order)
			{
				parent.Line = __Line.Where(c => c.OrderId == parent.OrderID).ToList();
			}
			
			response.Order = __Order;
		}
		catch(SqlException e)
		{
			errors.Add(CreateError(e));
		}
		
		if (!isOrder) errors.Add(new(51001, 12, 1, 151, "Order", "Expected return table `Order`"));
		if (!isCustomer) errors.Add(new(51001, 12, 1, 152, "Customer", "Expected return table `Customer`"));
		if (!isLine) errors.Add(new(51001, 12, 1, 153, "Line", "Expected return table `Line`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Order table(
			[OrderID] int,
			[CustomerId] int);
		
		Declare @Returns_Customer table(
			[CustomerID] int,
			[Name] varchar(50));
		
		Declare @Returns_Line table(
			[LineID] int,
			[OrderId] int,
			[Sku] varchar(20));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Order;
		Select * From @Returns_Customer;
		Select * From @Returns_Line;
		""";
	}
}
