//HintName: CustomTableVariableRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record CustomTableVariableRequest
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
	
	public System.Collections.Generic.List<CustomFile>? Table { get; set; } = [];
}
