namespace Microsoft.CodeAnalysis;

/// <summary>
/// Shared constants and code-generation fragments used throughout the generator.
/// Centralising these strings ensures the emitted C# type names stay consistent
/// with the names the generator looks up in the user's compilation.
/// </summary>
public static class SourceGeneratorHelper
{
	/// <summary>The root namespace for all SQuiL-emitted types: <c>SQuiL</c>.</summary>
	public static string NamespaceName { get; } = "SQuiL";

	/// <summary>MSBuild property / compiler-visible property key used to pass the solution root path.</summary>
	public static string ConfigRootPath { get; } = $"{NamespaceName}SolutionRoot";

	/// <summary>Short name of the query attribute class: <c>SQuiLQueryAttribute</c>.</summary>
	public static string QueryAttributeName { get; } = $"{NamespaceName}QueryAttribute";

	/// <summary>Short name of the table-type attribute class: <c>SQuiLTableAttribute</c>.</summary>
	public static string TableTypeAttributeName { get; } = $"{NamespaceName}TableAttribute";

	/// <summary>Fully-qualified name used when scanning the compilation for <c>[SQuiLQueryAttribute]</c>.</summary>
	public static string NamespacedQueryAttributeValue { get; } = $"{NamespaceName}.{QueryAttributeName}";

	/// <summary>Fully-qualified name used when scanning the compilation for <c>[SQuiLTableAttribute]</c>.</summary>
	public static string NamespacedTableTypeAttributeName { get; } = $"{NamespaceName}.{TableTypeAttributeName}";

	/// <summary>Short name of the result-type generic record: <c>SQuiLResultType</c>.</summary>
	public static string ResultTypeAttributeName { get; } = $"{NamespaceName}ResultType";

	/// <summary>Short name of the abstract base context class: <c>SQuiLBaseDataContext</c>.</summary>
	public static string BaseDataContextClassName { get; } = $"{NamespaceName}BaseDataContext";

	/// <summary>Default connection string key looked up in <c>IConfiguration</c>: <c>SQuiLDatabase</c>.</summary>
	public static string DefaultConnectionStringAppSettingName { get; } = $"{NamespaceName}Database";

	/// <summary>The <c>// &lt;auto-generated /&gt;</c> banner placed at the top of every emitted file.</summary>
	public static string AutoGenerated { get; } = """
		// <auto-generated />

		""";

	/// <summary>
	/// Full file header prepended to every emitted source file: auto-generated banner
	/// followed by <c>#nullable enable</c>.
	/// </summary>
	public static string FileHeader { get; } = $"""
		{AutoGenerated}
		#nullable enable

		""";
}
