//HintName: InputParameterTakesMaxStringConvertToTableArrayResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputParameterTakesMaxStringConvertToTableArrayResponse
{
}
