//HintName: InputParameterTakesMaxStringConvertToTableArrayRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputParameterTakesMaxStringConvertToTableArrayRequest
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
	
	public string? LongText { get; set; }
}
