//HintName: InputParameterTakesMaxStringConvertToTableArrayRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputParameterTakesMaxStringConvertToTableArrayRequest
{
	public string? LongText { get; set; }
}
