//HintName: InputParameterTakesMaxStringConvertToTableArrayDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;
using System.Data.Common;

using SQuiL;

namespace TestCase;

partial class InputParameterTakesMaxStringConvertToTableArrayDataContext : SQuiLBaseDataContext
{
	public async Task<InputParameterTakesMaxStringConvertToTableArrayResponse> ProcessInputParameterTakesMaxStringConvertToTableArrayAsync(
		InputParameterTakesMaxStringConvertToTableArrayRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length, EnvironmentName),
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, request.Debug || EnvironmentName != "Production"),
			CreateParameter("@Param_LongText", System.Data.SqlDbType.VarChar, -1, request.LongText ?? (object)System.DBNull.Value
			, p => p.IsNullable = true)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		await command.ExecuteNonQueryAsync(cancellationToken);
		
		return new();
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
