//HintName: TestCase.ReadOnlyUnderTransactionWarnsSP0024DataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class ReadOnlyUnderTransactionWarnsSP0024DataContext : SqlServerDataContext
{
    public ReadOnlyUnderTransactionWarnsSP0024DataContext(IConfiguration Configuration) : base(Configuration) { }
}
