//HintName: ReadOnlyUnderTransactionWarnsSP0024Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ReadOnlyUnderTransactionWarnsSP0024Response
{
	public int Count { get; set; }
}
