//HintName: ReadOnlyUnderTransactionWarnsSP0024DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ReadOnlyUnderTransactionWarnsSP0024DataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<ReadOnlyUnderTransactionWarnsSP0024Response>> ProcessReadOnlyUnderTransactionWarnsSP0024Async(
		ReadOnlyUnderTransactionWarnsSP0024Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_Id", System.Data.SqlDbType.BigInt, request.Id)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		using var transaction = connection.BeginTransaction();
		command.Transaction = transaction;
		
		ReadOnlyUnderTransactionWarnsSP0024Response response = new();
		
		var isCount = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Return_Count__":
						{
							if (isCount) throw new Exception(
								"Already returned value for `Count`");
							
							isCount = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							response.Count = !reader.IsDBNull(1) ? reader.GetInt32(1) : throw new NullReferenceException("Return value for Return_Count cannot be null.");
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isCount) errors.Add(new(51001, 12, 1, 79, "Count", "Expected return scaler `Count`"));
		
		if (errors.Count == 0)
			transaction.Commit();
		else
			transaction.Rollback();
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Count int;
		
		Use [{builder.InitialCatalog}];
		
		Set @Return_Count = (Select Count(*) From [Documents] Where Id = @Param_Id);
		Select 'Return_Count' As [__SQuiL__Table__Type__Return_Count__], @Return_Count;
		
		""";
	}
}
