//HintName: ReturnErrorTableEmitsNormallyDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ReturnErrorTableEmitsNormallyDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<ReturnErrorTableEmitsNormallyResponse>> ProcessReturnErrorTableEmitsNormallyAsync(
		ReturnErrorTableEmitsNormallyRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		ReturnErrorTableEmitsNormallyResponse response = new();
		
		var isError = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "number:int|severity:int|state:int|line:int|procedure:string|message:string":
					{
						if (isError) throw new Exception(
							"Already returned value for `Error`");
						
						isError = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						if (response.Error is not null)
							throw new Exception("Error was already set.");
						
						response.Error = new(
							reader.GetInt32(reader.GetOrdinal("Number")),
							reader.GetInt32(reader.GetOrdinal("Severity")),
							reader.GetInt32(reader.GetOrdinal("State")),
							reader.GetInt32(reader.GetOrdinal("Line")),
							reader.GetString(reader.GetOrdinal("Procedure")),
							reader.GetString(reader.GetOrdinal("Message")));
						
						if (await reader.ReadAsync(cancellationToken))
							throw new Exception(
								"Return object results in more than one object. Consider using a return table instead.");
						
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isError) errors.Add(new(51001, 12, 1, 86, "Error", "Expected return object `Error`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Error table(
			[Number] int,
			[Severity] int,
			[State] int,
			[Line] int,
			[Procedure] varchar(max),
			[Message] varchar(max));
		
		Use [{builder.InitialCatalog}];
		
		Select * From Return_Error;
		""";
	}
}
