//HintName: ReturnErrorTableEmitsNormallyResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ReturnErrorTableEmitsNormallyResponse
{
	public Error? Error { get; set; } = default!;
}
