//HintName: Error.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Error(
	int Number,
	int Severity,
	int State,
	int Line,
	string Procedure,
	string Message);
