//HintName: TwoDistinctOutputsRouteByShapeResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoDistinctOutputsRouteByShapeResponse
{
	public System.Collections.Generic.List<TestCase.Models.People>? People { get; set; }
	
	public System.Collections.Generic.List<TestCase.Models.Orders>? Orders { get; set; }
}
