//HintName: FullVariableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record FullVariableResponse
{
	public int Scaler { get; set; }
	
	public TestCase.Models.Object? Object { get; set; } = default!;
	
	public System.Collections.Generic.List<TestCase.Models.Table>? Table { get; set; }
}
