//HintName: FullVariableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record FullVariableResponse
{
	public int? Scaler { get; set; }
	
	public ObjectObject? Object { get; set; } = default!;
	
	public System.Collections.Generic.List<TableTable> Table { get; set; } = [];
}
