//HintName: FullVariableDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class FullVariableDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<FullVariableResponse>> ProcessFullVariableAsync(
		FullVariableRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, request.Debug || EnvironmentName != "Production"),
			CreateParameter("@Param_Scaler", System.Data.SqlDbType.Int, request.Scaler)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		FullVariableResponse response = new();
		
		var isScaler = false;
		var isObject = false;
		var isTable = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "scaler:int":
					{
						if (isScaler) throw new Exception(
							"Already returned value for `Scaler`");
						
						isScaler = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						response.Scaler = !reader.IsDBNull(0) ? reader.GetInt32(0) : throw new NullReferenceException("Return value for Scaler cannot be null.");
						break;
					}
					case "objectid:int|ismale:bool|firstname:string":
					{
						if (isObject) throw new Exception(
							"Already returned value for `Object`");
						
						isObject = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						if (response.Object is not null)
							throw new Exception("Object was already set.");
						
						response.Object = new(
							reader.GetInt32(reader.GetOrdinal("ObjectID")),
							reader.GetBoolean(reader.GetOrdinal("IsMale")),
							reader.GetString(reader.GetOrdinal("FirstName")));
						
						if (await reader.ReadAsync(cancellationToken))
							throw new Exception(
								"Return object results in more than one object. Consider using a return table instead.");
						
						break;
					}
					case "tableid:int|isfemale:bool|lastname:string":
					{
						isTable = true;
						
						response.Table ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexTableID = reader.GetOrdinal("TableID");
						var indexIsFemale = reader.GetOrdinal("IsFemale");
						var indexLastName = reader.GetOrdinal("LastName");
						
						do
						{
							var valueTableID = reader.GetInt32(indexTableID);
							var valueIsFemale = reader.GetBoolean(indexIsFemale);
							var valueLastName = reader.GetString(indexLastName);
							
							response.Table.Add(new(
								valueTableID,
								valueIsFemale,
								valueLastName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isScaler) errors.Add(new(51001, 12, 1, 124, "Scaler", "Expected return scaler `Scaler`"));
		if (!isObject) errors.Add(new(51001, 12, 1, 125, "Object", "Expected return object `Object`"));
		if (!isTable) errors.Add(new(51001, 12, 1, 126, "Table", "Expected return table `Table`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string inputObject(List<DbParameter> parameters)
		{
			if (request.Object is null)
				throw new NullReferenceException(
					"FullVariableRequest is missing the required property Object.");
			
			if (request.Object.FirstName is not null && request.Object.FirstName.Length > 100)
			{
				throw new Exception($"FullVariableRequest Object.FirstName exceeds its maximum length of 100 characters.");
			}
			
			AddJsonParameter(parameters, "@__json_Param_Object", new[] { request.Object });
			
			return """
			Insert Into @Param_Object([ObjectID], [IsMale], [FirstName])
			Select [ObjectID], [IsMale], [FirstName]
			From OpenJson(@__json_Param_Object)
			With (
				[ObjectID] int '$.ObjectID',
				[IsMale] bit '$.IsMale',
				[FirstName] varchar(100) '$.FirstName');
			""";
		}
		
		string inputTable(List<DbParameter> parameters)
		{
			if (request.Table is null || request.Table.Count == 0) return "";
			
			var index = 0;
			foreach (var item in request.Table)
			{
				if (item.LastName is not null && item.LastName.Length > 100)
				{
					throw new Exception($"FullVariableRequest Table[{index}].LastName exceeds its maximum length of 100 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Table", request.Table);
			
			return """
			Insert Into @Params_Table([TableID], [IsFemale], [LastName])
			Select [TableID], [IsFemale], [LastName]
			From OpenJson(@__json_Params_Table)
			With (
				[TableID] int '$.TableID',
				[IsFemale] bit '$.IsFemale',
				[LastName] varchar(100) '$.LastName');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Param_Object table(
			[ObjectID] int,
			[IsMale] bit,
			[FirstName] varchar(100));
		{inputObject(parameters)}
		
		Declare @Params_Table table(
			[TableID] int,
			[IsFemale] bit,
			[LastName] varchar(100));
		{inputTable(parameters)}
		
		Declare @Return_Scaler int;
		
		Declare @Return_Object table(
			[ObjectID] int,
			[IsMale] bit,
			[FirstName] varchar(100));
		
		Declare @Returns_Table table(
			[TableID] int,
			[IsFemale] bit,
			[LastName] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
