//HintName: TestCase.FullVariableDataContext.FullVariableObjectObject.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record FullVariableObjectObject(
	int ObjectID,
	bool IsMale,
	string FirstName,
	bool IsNeither,
	string PreferredName);
