//HintName: TableTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TableTable(
	int TableID,
	bool IsFemale,
	string LastName,
	bool IsBoth,
	string NickName);
