//HintName: ObjectObject.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ObjectObject(
	int ObjectID,
	bool IsMale,
	string FirstName,
	bool IsNeither,
	string PreferredName);
