//HintName: CustomCtorDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class CustomCtorDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<CustomCtorResponse>> ProcessCustomCtorAsync(
		CustomCtorRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		CustomCtorResponse response = new();
		
		var isCount = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Return_Count__":
						{
							if (isCount) throw new Exception(
								"Already returned value for `Count`");
							
							isCount = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							response.Count = !reader.IsDBNull(1) ? reader.GetInt32(1) : null;
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isCount) errors.Add(new(51001, 12, 1, 75, "Count", "Expected return scaler `Count`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Count int;
		
		Use [{builder.InitialCatalog}];
		
		Select @Return_Count = 1;
		Select 'Return_Count' As [__SQuiL__Table__Type__Return_Count__], @Return_Count;
		
		""";
	}
}
