//HintName: SpecialVariablePlacementIsEnforcedRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SpecialVariablePlacementIsEnforcedRequest
{
	public bool Debug { get; set; }
	
	public string Name { get; set; }
}
