//HintName: SpecialVariablePlacementIsEnforcedResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SpecialVariablePlacementIsEnforcedResponse
{
	public int? Count { get; set; }
}
