//HintName: TimestampOutputIsAllowedResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TimestampOutputIsAllowedResponse
{
	public byte[] Version { get; set; }
}
