//HintName: EmbeddedObjectChildInputNestingDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class EmbeddedObjectChildInputNestingDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessEmbeddedObjectChildInputNestingAsync(
		EmbeddedObjectChildInputNestingRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		List<TestCase.Models.Order> __Order = [];
		List<TestCase.Models.Shipment> __Shipment = [];
		
		if (request.Order is not null)
		{
			var orderKey = __Order.Count + 1;
			__Order.Add(new(
				orderKey,
				request.Order.CustomerName));
			if (request.Order.Shipment is not null)
			{
				var shipment = request.Order.Shipment;
				var shipmentKey = __Shipment.Count + 1;
				__Shipment.Add(new(
					shipmentKey,
					orderKey,
					shipment.Carrier));
			}
		}
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputOrder(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Order)
			{
				if (item.CustomerName is not null && item.CustomerName.Length > 50)
				{
					throw new Exception($"EmbeddedObjectChildInputNestingRequest Order[{index}].CustomerName exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Param_Order", __Order);
			
			return """
			Insert Into @Param_Order([OrderID], [CustomerName])
			Select [OrderID], [CustomerName]
			From OpenJson(@__json_Param_Order)
			With (
				[OrderID] int '$.OrderID',
				[CustomerName] varchar(50) '$.CustomerName');
			""";
		}
		
		string inputShipment(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Shipment)
			{
				if (item.Carrier is not null && item.Carrier.Length > 50)
				{
					throw new Exception($"EmbeddedObjectChildInputNestingRequest Shipment[{index}].Carrier exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Param_Shipment", __Shipment);
			
			return """
			Insert Into @Param_Shipment([ShipmentID], [OrderID], [Carrier])
			Select [ShipmentID], [OrderID], [Carrier]
			From OpenJson(@__json_Param_Shipment)
			With (
				[ShipmentID] int '$.ShipmentID',
				[OrderID] int '$.OrderID',
				[Carrier] varchar(50) '$.Carrier');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Param_Order table(
			[OrderID] int,
			[CustomerName] varchar(50));
		{inputOrder(parameters)}
		
		Declare @Param_Shipment table(
			[ShipmentID] int,
			[OrderID] int,
			[Carrier] varchar(50));
		{inputShipment(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Insert Into dbo.Orders Select OrderID, CustomerName From @Param_Order;
		Insert Into dbo.Shipments Select ShipmentID, OrderID, Carrier From @Param_Shipment;
		""";
	}
}
