//HintName: EmbeddedObjectChildInputNestingRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record EmbeddedObjectChildInputNestingRequest
{
	public TestCase.Models.Order? Order { get; set; } = default!;
}
