//HintName: Structure.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Structure(
	string Title)
{
	public TestCase.Models.Contact? Contact { get; set; }
}
