//HintName: Debug_declared_gates_commit_on_the_debug_expressionRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Debug_declared_gates_commit_on_the_debug_expressionRequest
{
	public bool Debug { get; set; }
	
	public System.Collections.Generic.List<TestCase.Models.Widget>? Widget { get; set; } = [];
}
