//HintName: TestCase.C.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class C : SqlServerDataContext
{
    public C(IConfiguration Configuration) : base(Configuration) { }
}
