//HintName: SQuiLQueryTransactionAttribute.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
public class SQuiLQueryTransactionAttribute : System.Attribute
{
	public QueryFiles Type { get; }

	public string Setting { get; }

	public bool Enabled { get; }

	public bool DebugRollback { get; }

	public SQuiLQueryTransactionAttribute(
		QueryFiles type,
		string setting = "SQuiLDatabase",
		bool enabled = true,
		bool debugRollback = true)
	{
		Type = type;
		Setting = setting;
		Enabled = enabled;
		DebugRollback = debugRollback;
	}
}