//HintName: TestCase.InputVariableDataContext.InputVariableRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputVariableRequest
{
	public bool Debug { get; set; }
	
	public int? Scaler { get; set; }
	
	public InputVariableRequestObjectTable Object { get; set; } = default!;
	
	public System.Collections.Generic.List<InputVariableRequestTableTable> Table { get; set; } = [];
}
