//HintName: TestCase.InputVariableDataContext.InputVariableRequestObjectTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputVariableRequestObjectTable(
	int ObjectID,
	bool IsMale,
	string FirstName);
