//HintName: TestCase.InputVariableDataContext.InputVariableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record InputVariableResponse
{
	public int? Scaler { get; set; }
	
	public InputVariableResponseObjectTable Object { get; set; } = default!;
	
	public System.Collections.Generic.List<InputVariableResponseTableTable> Table { get; set; } = [];
}
