//HintName: Order.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Order(
	int OrderID)
{
	public TestCase.Models.Customer? Customer { get; set; }
	public System.Collections.Generic.List<TestCase.Models.Line>? Line { get; set; } = [];
}
