//HintName: CaseMismatchedKeyInputDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class CaseMismatchedKeyInputDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType> ProcessCaseMismatchedKeyInputAsync(
		CaseMismatchedKeyInputRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		List<TestCase.Models.Order> __Order = [];
		List<int> __Order__CustomerId = [];
		List<TestCase.Models.Customer> __Customer = [];
		var __CustomerSeen = new Dictionary<int, TestCase.Models.Customer>();
		List<TestCase.Models.Line> __Line = [];
		
		foreach (var order in request.Order ?? [])
		{
			var orderKey = (int)(__Order.Count + 1);
			__Order.Add(new(
				orderKey));
			__Order__CustomerId.Add((order.Customer ?? throw new InvalidOperationException("CaseMismatchedKeyInputRequest Order.Customer is required: it supplies the not-null CustomerId column.")).CustomerID);
			if (order.Customer is not null)
			{
				var customer = order.Customer;
				var __CustomerRow = new TestCase.Models.Customer(
					customer.CustomerID,
					customer.Name);
				if (__CustomerSeen.TryGetValue(__CustomerRow.CustomerID, out var __CustomerPrev))
				{
					if (__CustomerPrev.CustomerID != __CustomerRow.CustomerID || __CustomerPrev.Name != __CustomerRow.Name)
					{
						throw new Exception($"Conflicting values supplied for Customer with CustomerID '{__CustomerRow.CustomerID}'.");
					}
				}
				else
				{
					__CustomerSeen[__CustomerRow.CustomerID] = __CustomerRow;
					__Customer.Add(__CustomerRow);
				}
			}
			foreach (var line in order.Line ?? [])
			{
				__Line.Add(new(
					line.LineID,
					orderKey,
					line.Sku));
			}
		}
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(SqlException e)
		{
			return new SQuiLResultType(CreateError(e));
		}
		
		string inputOrder(List<DbParameter> parameters)
		{
			AddJsonParameter(parameters, "@__json_Params_Order", System.Linq.Enumerable.ToList(System.Linq.Enumerable.Select(__Order, (__r, __i) => new { OrderID = __r.OrderID, CustomerId = __Order__CustomerId[__i] })));
			
			return """
			Insert Into @Params_Order([OrderID], [CustomerId])
			Select [OrderID], [CustomerId]
			From OpenJson(@__json_Params_Order)
			With (
				[OrderID] int '$.OrderID',
				[CustomerId] int '$.CustomerId');
			""";
		}
		
		string inputCustomer(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Customer)
			{
				if (item.Name is not null && item.Name.Length > 50)
				{
					throw new Exception($"CaseMismatchedKeyInputRequest Customer[{index}].Name exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Customer", __Customer);
			
			return """
			Insert Into @Params_Customer([CustomerID], [Name])
			Select [CustomerID], [Name]
			From OpenJson(@__json_Params_Customer)
			With (
				[CustomerID] int '$.CustomerID',
				[Name] varchar(50) '$.Name');
			""";
		}
		
		string inputLine(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Line)
			{
				if (item.Sku is not null && item.Sku.Length > 20)
				{
					throw new Exception($"CaseMismatchedKeyInputRequest Line[{index}].Sku exceeds its maximum length of 20 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Line", __Line);
			
			return """
			Insert Into @Params_Line([LineID], [OrderId], [Sku])
			Select [LineID], [OrderId], [Sku]
			From OpenJson(@__json_Params_Line)
			With (
				[LineID] int '$.LineID',
				[OrderId] int '$.OrderId',
				[Sku] varchar(20) '$.Sku');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Order table(
			[OrderID] int,
			[CustomerId] int);
		{inputOrder(parameters)}
		
		Declare @Params_Customer table(
			[CustomerID] int,
			[Name] varchar(50));
		{inputCustomer(parameters)}
		
		Declare @Params_Line table(
			[LineID] int,
			[OrderId] int,
			[Sku] varchar(20));
		{inputLine(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Insert Into dbo.Orders Select OrderID, CustomerId From @Params_Order;
		Insert Into dbo.Customers Select CustomerID, Name From @Params_Customer;
		Insert Into dbo.Lines Select LineID, OrderId, Sku From @Params_Line;
		""";
	}
}
