//HintName: ScalarVariableDefaultsDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ScalarVariableDefaultsDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessScalarVariableDefaultsAsync(
		ScalarVariableDefaultsRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_Id", System.Data.SqlDbType.UniqueIdentifier, request.Id),
			CreateParameter("@Param_AmountWhole", System.Data.SqlDbType.Decimal, request.AmountWhole),
			CreateParameter("@Param_Count", System.Data.SqlDbType.BigInt, request.Count),
			CreateParameter("@Param_Ratio", System.Data.SqlDbType.Float, request.Ratio),
			CreateParameter("@Param_Flag", System.Data.SqlDbType.Bit, request.Flag),
			CreateParameter("@Param_Label", System.Data.SqlDbType.VarChar, 50, request.Label switch
			{
				null => (object)System.DBNull.Value,
				{ Length: <= 50 } => request.Label,
				_ => throw new Exception(
					"Request model data is larger then database size for the property [Label].")
			})
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
