//HintName: ScalarVariableDefaultsRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ScalarVariableDefaultsRequest
{
	public System.Guid Id { get; set; } = System.Guid.Parse("12345678-1234-1234-1234-123456789012");
	
	public decimal AmountWhole { get; set; } = 5;
	
	public int Count { get; set; } = 7;
	
	public double Ratio { get; set; } = 2;
	
	public bool Flag { get; set; } = true;
	
	public string Label { get; set; } = "hello";
}
