namespace SquilParser.SourceGenerator.Parser;

[Flags]
public enum CodeType
{
	USING = 1,
	BODY = 1 << 2,
	INPUT = 1 << 3,
	INPUT_ARGUMENT = INPUT | ARGUMENT,
	INPUT_OBJECT = INPUT | OBJECT,
	INPUT_TABLE = INPUT | TABLE,
	OUTPUT = 1 << 4,
	OUTPUT_VARIABLE = OUTPUT | VARIABLE,
	OUTPUT_OBJECT = OUTPUT | OBJECT,
	OUTPUT_TABLE = OUTPUT | TABLE,
	ARGUMENT = 1 << 5,
	VARIABLE = ARGUMENT,
	OBJECT = 1 << 6,
	TABLE = 1 << 7,
	INVALID = 0
};
