//HintName: EmbeddedLookupResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record EmbeddedLookupResponse
{
	public System.Collections.Generic.List<TestCase.Models.Structure>? Structure { get; set; }
}
