//HintName: GuidNonNullDefaultCompilesRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record GuidNonNullDefaultCompilesRequest
{
	public System.Guid Key { get; set; } = System.Guid.Parse("00000000-0000-0000-0000-000000000001");
}
