//HintName: ObjectPropertyNullableRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ObjectPropertyNullableRequest
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
}
