//HintName: ObjectPropertyNullableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ObjectPropertyNullableResponse
{
	public TestCase.Models.Student? Student { get; set; } = default!;
	
	public System.Collections.Generic.List<TestCase.Models.Parents>? Parents { get; set; }
}
