//HintName: UseStatementFailsWhenAddingDeclareTestResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record UseStatementFailsWhenAddingDeclareTestResponse
{
	public System.Collections.Generic.List<TestCase.Models.ExtendedCourses>? ExtendedCourses { get; set; }
}
