//HintName: ColumnDefaultBeforeRequiredIsErrorDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ColumnDefaultBeforeRequiredIsErrorDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessColumnDefaultBeforeRequiredIsErrorAsync(
		ColumnDefaultBeforeRequiredIsErrorRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputBad(List<DbParameter> parameters)
		{
			System.Text.StringBuilder query = new();
			query.Append("Insert Into @Params_Bad([Amount], [Note])");
			
			if (request.Bad.Count() == 0) return "";
			
			query.AppendLine(" Values");
			
			var comma = "";
			var index = 0;
			
			foreach(var item in request.Bad)
			{
				index++;
				
				query.AppendLine(comma);
				query.Append('(');
				AddParams(query, parameters, index, "ParamsBad", "Amount", System.Data.SqlDbType.Decimal, item.Amount);
				query.Append(", ");
				AddParams(query, parameters, index, "ParamsBad", "Note", System.Data.SqlDbType.VarChar, item.Note, 50);
				query.Append(')');
				
				comma = ",";
			}
			
			query.AppendLine(";");
			query.AppendLine();
			
			return query.ToString();
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Bad table(
			[__SQuiL__Table__Type__Params_Bad__] varchar(max) default('Params_Bad'),
			[Amount] decimal(18,2),
			[Note] varchar(50));
		{inputBad(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
