//HintName: TwoQueriesWithSameReference1Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueriesWithSameReference1Response
{
	public System.Collections.Generic.List<MergedData> Questions { get; set; } = [];
}
