//HintName: TwoQueriesWithSameReference1DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;
using System.Data.Common;

using SQuiL;

namespace TestCase;

partial class TwoQueriesWithSameReferenceDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<TwoQueriesWithSameReference1Response>> ProcessTwoQueriesWithSameReference1Async(
		TwoQueriesWithSameReference1Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length, EnvironmentName),
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, request.Debug || EnvironmentName != "Production")
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		TwoQueriesWithSameReference1Response response = new();
		
		var isQuestions = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Error__":
						{
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							break;
						}
						case "__SQuiL__Table__Type__Returns_Questions__":
						{
							isQuestions = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexNumber = reader.GetOrdinal("Number");
							var indexMessage = reader.GetOrdinal("Message");
							
							do
							{
								if (reader.GetString(0) == "Returns_Questions")
								{
										var valueNumber = reader.GetInt32(indexNumber);
										var valueMessage = reader.GetString(indexMessage);
										
									response.Questions.Add(new(
											valueNumber,
											valueMessage));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isQuestions) errors.Add(new(51001, 12, 1, 90, "Questions", "Expected return table `Questions`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Questions table(
			[__SQuiL__Table__Type__Returns_Questions__] varchar(max) default('Returns_Questions'),
			[Number] int,
			[Message] varchar(max));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Questions;
		
		""";
	}
}
