//HintName: TwoQueriesWithSameReference2Request.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueriesWithSameReference2Request
{
	public bool Debug { get; set; }
	
	public MergedData? Question { get; set; } = default!;
}
