//HintName: TwoQueriesWithSameReference2DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class TwoQueriesWithSameReferenceDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessTwoQueriesWithSameReference2Async(
		TwoQueriesWithSameReference2Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputQuestion(List<DbParameter> parameters)
		{
			if (request.Question is null)
				throw new NullReferenceException(
					"TwoQueriesWithSameReference2Request is missing the required property Question.");
			
			AddJsonParameter(parameters, "@__json_Param_Question", new[] { request.Question });
			
			return """
			Insert Into @Param_Question([Number], [Message])
			Select [Number], [Message]
			From OpenJson(@__json_Param_Question)
			With (
				[Number] int '$.Number',
				[Message] varchar(max) '$.Message');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Param_Question table(
			[Number] int,
			[Message] varchar(max));
		{inputQuestion(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Param_Question;
		""";
	}
}
