//HintName: TwoQueriesWithSameReference2DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;
using System.Data.Common;

using SQuiL;

namespace TestCase;

partial class TwoQueriesWithSameReferenceDataContext : SQuiLBaseDataContext
{
	public async Task<TwoQueriesWithSameReference2Response> ProcessTwoQueriesWithSameReference2Async(
		TwoQueriesWithSameReference2Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);

		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length, EnvironmentName),
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, request.Debug || EnvironmentName != "Production")
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		await command.ExecuteNonQueryAsync(cancellationToken);
		
		return new();
		
		string inputQuestion(List<DbParameter> parameters)
		{
			System.Text.StringBuilder query = new();
			query.Append("Insert Into @Param_Question([Number], [Message])");

			if (request.Question is null)
				throw new NullReferenceException(
					"TwoQueriesWithSameReference2Request is missing the required property Question.");
			
			query.AppendLine();
			query.Append("Values (");
			
			AddParams(query, parameters, 0, "ParamQuestion", "Number", System.Data.SqlDbType.BigInt, request.Question.Number);
			query.Append(", ");
			AddParams(query, parameters, 0, "ParamQuestion", "Message", System.Data.SqlDbType.VarChar, request.Question.Message, request.Question.Message?.Length ?? 4096);
			
			query.Append(')');
			query.AppendLine(";");
			query.AppendLine();
			
			return query.ToString();
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Param_Question table(
			[__SQuiL__Table__Type__Param_Question__] varchar(max) default('Param_Question'),
			[Number] int,
			[Message] varchar(max));
		{inputQuestion(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Param_Question;
		
		""";
	}
}
