//HintName: TwoQueriesWithSameReference2Request.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueriesWithSameReference2Request
{
	public TestCase.Models.Question? Question { get; set; } = default!;
}
