//HintName: QueryHasErrorObjectResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record QueryHasErrorObjectResponse
{
	public int? SampleID { get; set; }
	
	public SampleEntityObject? SampleEntity { get; set; } = default!;
	
	public System.Collections.Generic.List<SamplesTable> Samples { get; set; } = [];
}
