//HintName: EmbeddedObjectChildDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

using SQuiL;

namespace TestCase;

partial class EmbeddedObjectChildDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<EmbeddedObjectChildResponse>> ProcessEmbeddedObjectChildAsync(
		EmbeddedObjectChildRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		EmbeddedObjectChildResponse response = new();
		
		var isTranscript = false;
		var isStudent = false;
		
		List<SQuiLError> errors = [];
		try
		{
			List<TestCase.Models.Transcript> __Transcript = [];
			List<TestCase.Models.Student> __Student = [];
			
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "transcriptid:int|issuedate:System.DateOnly":
					{
						isTranscript = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexTranscriptID = reader.GetOrdinal("TranscriptID");
						var indexIssueDate = reader.GetOrdinal("IssueDate");
						
						do
						{
							var valueTranscriptID = reader.GetInt32(indexTranscriptID);
							var valueIssueDate = reader.GetFieldValue<System.DateOnly>(indexIssueDate);
							
							__Transcript.Add(new(
								valueTranscriptID,
								valueIssueDate));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "studentid:int|transcriptid:int|firstname:string":
					{
						isStudent = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexStudentID = reader.GetOrdinal("StudentID");
						var indexTranscriptID = reader.GetOrdinal("TranscriptID");
						var indexFirstName = reader.GetOrdinal("FirstName");
						
						do
						{
							var valueStudentID = reader.GetInt32(indexStudentID);
							var valueTranscriptID = reader.GetInt32(indexTranscriptID);
							var valueFirstName = reader.GetString(indexFirstName);
							
							__Student.Add(new(
								valueStudentID,
								valueTranscriptID,
								valueFirstName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
			
			foreach (var parent in __Transcript)
			{
				parent.Student = System.Linq.Enumerable.SingleOrDefault(__Student.Where(c => c.TranscriptID == parent.TranscriptID));
			}
			
			response.Transcript = System.Linq.Enumerable.SingleOrDefault(__Transcript);
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isTranscript) errors.Add(new(51001, 12, 1, 117, "Transcript", "Expected return object `Transcript`"));
		if (!isStudent) errors.Add(new(51001, 12, 1, 118, "Student", "Expected return object `Student`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Transcript table(
			[TranscriptID] int,
			[IssueDate] date);
		
		Declare @Return_Student table(
			[StudentID] int,
			[TranscriptID] int,
			[FirstName] varchar(50));
		
		Use [{builder.InitialCatalog}];
		
		Insert Into @Return_Transcript Select TranscriptID, IssueDate From T;
		Insert Into @Return_Student Select StudentID, TranscriptID, FirstName From S;
		Select * From @Return_Transcript;
		Select * From @Return_Student;
		""";
	}
}
