//HintName: Transcript.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Transcript(
	int TranscriptID,
	System.DateOnly IssueDate)
{
	public TestCase.Models.Student? Student { get; set; }
}
