//HintName: TwoQueriesWithMismatchedShapes2Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueriesWithMismatchedShapes2Response
{
	public System.Collections.Generic.List<QuestionsTable> Questions { get; set; } = [];
}
