//HintName: TwoQueriesWithMismatchedShapes2Request.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueriesWithMismatchedShapes2Request
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
}
