//HintName: TwoQueriesWithMismatchedShapes2DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class TwoQueriesWithMismatchedShapesDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<TwoQueriesWithMismatchedShapes2Response>> ProcessTwoQueriesWithMismatchedShapes2Async(
		TwoQueriesWithMismatchedShapes2Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		TwoQueriesWithMismatchedShapes2Response response = new();
		
		var isQuestions = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Returns_Questions__":
						{
							isQuestions = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexNumber = reader.GetOrdinal("Number");
							var indexTopic = reader.GetOrdinal("Topic");
							
							do
							{
								if (reader.GetString(0) == "Returns_Questions")
								{
									var valueNumber = reader.GetInt32(indexNumber);
									var valueTopic = reader.GetString(indexTopic);
									
									response.Questions.Add(new(
										valueNumber,
										valueTopic));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isQuestions) errors.Add(new(51001, 12, 1, 87, "Questions", "Expected return table `Questions`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Questions table(
			[__SQuiL__Table__Type__Returns_Questions__] varchar(max) default('Returns_Questions'),
			[Number] int,
			[Topic] varchar(50));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Questions;
		
		""";
	}
}
