//HintName: TwoQueriesWithMismatchedShapes1Request.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueriesWithMismatchedShapes1Request
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
}
