//HintName: GuidKeyInputNestingRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record GuidKeyInputNestingRequest
{
	public TestCase.Models.Order? Order { get; set; } = default!;
}
