using System.Collections.Generic;
using System.Linq;
using System.Text;
using SQuiL.SsmsExtension.Parsing;

namespace SQuiL.SsmsExtension.Preview;

/// <summary>
/// Generates a human-readable preview of the C# the SQuiL source generator
/// will emit for a given .squil file.  Port of
/// <c>SQuiL.VSCodeExtension/src/squil/previewGenerator.ts</c>.
///
/// This is a *preview* — not an exact reproduction of generator output.  It
/// captures the structure (records, request/response, data context method,
/// DI hint) so a developer can sanity-check their SQL declarations without
/// running <c>dotnet build</c>.  Run-time output may differ in trivial
/// formatting; for byte-exact code, use the Build SQuiL Project command.
/// </summary>
internal static class SQuiLPreviewGenerator
{
    /// <summary>
    /// Record-type name for a TABLE-valued variable:
    ///   • <c>Params</c>/<c>Returns</c> → <c>&lt;Name&gt;Table</c> (collection element)
    ///   • <c>ParamTable</c>/<c>ReturnTable</c> → <c>&lt;Name&gt;Object</c> (single object)
    /// Matches the convention recorded in CLAUDE.md.
    /// </summary>
    private static string RecordTypeName(SQuiLVariable v) => v.Role switch
    {
        VariableRole.Params      => $"{v.Name}Table",
        VariableRole.Returns     => $"{v.Name}Table",
        VariableRole.ParamTable  => $"{v.Name}Object",
        VariableRole.ReturnTable => $"{v.Name}Object",
        _                        => v.Name,
    };

    private static string GetPropertyType(SQuiLVariable v)
    {
        if (v.Role is VariableRole.Params or VariableRole.Returns)
            return $"List<{RecordTypeName(v)}>?";
        if (v.Role is VariableRole.ParamTable or VariableRole.ReturnTable)
            return $"{RecordTypeName(v)}?";

        // Scalars: ref types get `?`, value types stay as-is.
        string cs = SqlTypeMap.SqlToCSharp(v.SqlType);
        return SqlTypeMap.IsRefType(v.SqlType) ? $"{cs}?" : cs;
    }

    private static bool IsCollection(SQuiLVariable v) =>
        v.Role is VariableRole.Params or VariableRole.Returns;

    public static string Generate(SQuiLParseResult parsed, string queryName, string ns = "YourNamespace")
    {
        string db = parsed.Database ?? "/* database */";
        var lines = new List<string>();

        var paramVars = parsed.Variables.Where(v =>
            v.Role is VariableRole.Param or VariableRole.Params or VariableRole.ParamTable).ToList();
        var returnVars = parsed.Variables.Where(v =>
            v.Role is VariableRole.Return or VariableRole.Returns or VariableRole.ReturnTable).ToList();

        EmitBanner(lines, queryName, db);
        lines.Add("");
        lines.Add($"namespace {ns};");
        lines.Add("");

        // ── QueryFiles enum hint ────────────────────────────────────────
        lines.Add("// ── QueryFiles enum entry ────────────────────────────────");
        lines.Add("// Generated by SQuiL.SourceGenerator — do not edit manually.");
        lines.Add("// Your QueryFiles enum will include:");
        lines.Add($"//   public enum QueryFiles {{ ..., {queryName} }}");
        lines.Add("");

        // ── Table-row records (input side) ──────────────────────────────
        foreach (var v in paramVars)
            if (v.Columns is { Count: > 0 })
                EmitTableRecord(lines, RecordTypeName(v), v);

        // ── Request record (always partial; specials are opt-in) ──
        lines.Add("// ── Request ─────────────────────────────────────────────");
        EmitModelRecord(lines, $"{queryName}Request", paramVars, isResponse: false, parsed.Variables);

        // ── Table-row records (output side) ─────────────────────────────
        foreach (var v in returnVars)
            if (v.Columns is { Count: > 0 })
                EmitTableRecord(lines, RecordTypeName(v), v);

        // ── Response record ─────────────────────────────────────────────
        if (returnVars.Count > 0)
        {
            lines.Add("// ── Response ────────────────────────────────────────────");
            EmitModelRecord(lines, $"{queryName}Response", returnVars, isResponse: true);
        }

        // ── Data context ────────────────────────────────────────────────
        lines.Add("// ── DataContext ─────────────────────────────────────────");
        lines.Add("// SQuiL emits this method into your partial class. You may omit the");
        lines.Add("// base type and constructor — SQuiL supplies both when absent:");
        lines.Add($"//   public partial class {queryName}DataContext {{ }}");
        lines.Add("// (Add your own constructor to customize; it must call : base(configuration).)");
        lines.Add("");

        string responseType = returnVars.Count == 0
            ? "SQuiLResultType"
            : $"SQuiLResultType<{queryName}Response>";

        lines.Add($"public async Task<{responseType}> Process{queryName}Async(");
        lines.Add($"    {queryName}Request request,");
        lines.Add("    CancellationToken cancellationToken = default!)");
        lines.Add("{");
        lines.Add("    /* generated body */");
        lines.Add("}");
        lines.Add("");

        // ── DI extension hint ───────────────────────────────────────────
        lines.Add("// ── Dependency Injection ────────────────────────────────");
        lines.Add("// SQuiL emits an AddSQuiL extension that registers every data context:");
        lines.Add("//");
        lines.Add("//   builder.AddSQuiL();");
        lines.Add("//");
        lines.Add($"// Connection string key: \"ConnectionStrings:{db}\"");

        return string.Join("\r\n", lines);
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private static void EmitBanner(List<string> lines, string queryName, string db)
    {
        lines.Add("// ╔═══════════════════════════════════════════════════════╗");
        lines.Add("// ║  SQuiL Generated C# Preview                          ║");
        lines.Add("// ╠═══════════════════════════════════════════════════════╣");
        lines.Add($"// ║  Query    : {Pad(queryName, 41)}║");
        lines.Add($"// ║  Database : {Pad(db, 41)}║");
        lines.Add("// ╠═══════════════════════════════════════════════════════╣");
        lines.Add("// ║  ⚠  This is a PREVIEW only.                          ║");
        lines.Add("// ║     Actual code is emitted by SQuiL.SourceGenerator  ║");
        lines.Add("// ║     when you run  dotnet build.                       ║");
        lines.Add("// ╚═══════════════════════════════════════════════════════╝");
    }

    private static string Pad(string s, int len) =>
        s.Length >= len ? s.Substring(0, len) : s + new string(' ', len - s.Length);

    private static void EmitTableRecord(List<string> lines, string typeName, SQuiLVariable v)
    {
        if (v.Columns is null || v.Columns.Count == 0) return;

        lines.Add($"public partial record {typeName}");
        lines.Add("{");
        foreach (var col in v.Columns)
        {
            string cs = SqlTypeMap.SqlToCSharp(col.SqlType);
            bool nullable = col.Nullable || SqlTypeMap.IsRefType(col.SqlType);
            string suffix = nullable ? "?" : "";
            lines.Add($"    public {cs}{suffix} {col.Name} {{ get; set; }}");
        }
        lines.Add("}");
        lines.Add("");
    }

    private static void EmitModelRecord(
        List<string> lines, string typeName, List<SQuiLVariable> vars, bool isResponse,
        IReadOnlyList<SQuiLVariable>? allVars = null)
    {
        lines.Add($"public partial record {typeName}");
        lines.Add("{");

        // *Request specials are OPT-IN — each appears only when its bare special
        // is declared in the SQL header.  @Debug → bool Debug, @SuppressDebug →
        // bool SuppressDebug (replaces the old always-on DebugOnly), @AsOfDate →
        // a nullable typed property.  @EnvironmentName is a sent parameter only,
        // never a property.
        if (!isResponse)
        {
            var declared = allVars ?? new List<SQuiLVariable>();
            bool hasDebug = declared.Any(v => v.Role == VariableRole.Debug);
            bool hasSuppressDebug = declared.Any(v => v.Role == VariableRole.SuppressDebug);
            var asOfDate = declared.FirstOrDefault(v => v.Role == VariableRole.AsOfDate);

            if (hasDebug) lines.Add("    public bool Debug { get; set; }");
            if (hasSuppressDebug) lines.Add("    public bool SuppressDebug { get; set; }");
            if (asOfDate != null)
            {
                // Take only the type token (drop any "= default" the SQL initializer
                // adds), matching the generator which maps the bare declared type.
                // AsOfDate is always nullable on *Request.
                string asOfType = asOfDate.SqlType.Split(new[] { ' ', '=' }, 2)[0];
                lines.Add($"    public {SqlTypeMap.SqlToCSharp(asOfType)}? AsOfDate {{ get; set; }}");
            }

            if ((hasDebug || hasSuppressDebug || asOfDate != null) && vars.Count > 0) lines.Add("");
        }

        foreach (var v in vars)
        {
            string type = GetPropertyType(v);
            string initializer = IsCollection(v) ? " = []" : "";
            lines.Add($"    public {type} {v.Name} {{ get; set; }}{initializer};");
        }

        lines.Add("}");
        lines.Add("");
    }
}
