//HintName: SharedLookupResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SharedLookupResponse
{
	public System.Collections.Generic.List<TestCase.Models.Structure>? Structure { get; set; }
	
	public System.Collections.Generic.List<TestCase.Models.Widget>? Widget { get; set; }
}
