//HintName: SharedLookupDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

using SQuiL;

namespace TestCase;

partial class SharedLookupDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType<SharedLookupResponse>> ProcessSharedLookupAsync(
		SharedLookupRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		SharedLookupResponse response = new();
		
		var isStructure = false;
		var isWidget = false;
		var isContact = false;
		
		List<SQuiLError> errors = [];
		try
		{
			List<TestCase.Models.Structure> __Structure = [];
			List<string> __Structure__ContactID = [];
			List<TestCase.Models.Widget> __Widget = [];
			List<string> __Widget__ContactID = [];
			List<TestCase.Models.Contact> __Contact = [];
			
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "title:string|contactid:string":
					{
						isStructure = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexTitle = reader.GetOrdinal("Title");
						var indexContactID = reader.GetOrdinal("ContactID");
						
						do
						{
							var valueTitle = reader.GetString(indexTitle);
							var valueContactID = reader.GetString(indexContactID);
							
							__Structure.Add(new(
								valueTitle));
							__Structure__ContactID.Add(valueContactID);
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "label:string|contactid:string":
					{
						isWidget = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexLabel = reader.GetOrdinal("Label");
						var indexContactID = reader.GetOrdinal("ContactID");
						
						do
						{
							var valueLabel = reader.GetString(indexLabel);
							var valueContactID = reader.GetString(indexContactID);
							
							__Widget.Add(new(
								valueLabel));
							__Widget__ContactID.Add(valueContactID);
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "contactid:string|name:string":
					{
						isContact = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexContactID = reader.GetOrdinal("ContactID");
						var indexName = reader.GetOrdinal("Name");
						
						do
						{
							var valueContactID = reader.GetString(indexContactID);
							var valueName = reader.GetString(indexName);
							
							__Contact.Add(new(
								valueContactID,
								valueName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
			
			for (var __i = 0; __i < __Structure.Count; __i++)
			{
				var __fk = __Structure__ContactID[__i];
				var __match = __Contact.Where(c => c.ContactID == __fk).ToList();
				if (__match.Count > 1)
				{
					throw new Exception("Return object results in more than one object. Consider using a return table instead.");
				}
				__Structure[__i].Contact = __match.Count == 1 ? __match[0] : null;
			}
			for (var __i = 0; __i < __Widget.Count; __i++)
			{
				var __fk = __Widget__ContactID[__i];
				var __match = __Contact.Where(c => c.ContactID == __fk).ToList();
				if (__match.Count > 1)
				{
					throw new Exception("Return object results in more than one object. Consider using a return table instead.");
				}
				__Widget[__i].Contact = __match.Count == 1 ? __match[0] : null;
			}
			
			response.Structure = __Structure;
			response.Widget = __Widget;
		}
		catch(SqlException e)
		{
			errors.Add(CreateError(e));
		}
		
		if (!isStructure) errors.Add(new(51001, 12, 1, 156, "Structure", "Expected return table `Structure`"));
		if (!isWidget) errors.Add(new(51001, 12, 1, 157, "Widget", "Expected return table `Widget`"));
		if (!isContact) errors.Add(new(51001, 12, 1, 158, "Contact", "Expected return table `Contact`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Structure table(
			[Title] varchar(50),
			[ContactID] varchar(10));
		
		Declare @Returns_Widget table(
			[Label] varchar(50),
			[ContactID] varchar(10));
		
		Declare @Returns_Contact table(
			[ContactID] varchar(10),
			[Name] varchar(50));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Structure;
		Select * From @Returns_Widget;
		Select * From @Returns_Contact;
		""";
	}
}
