//HintName: SQuiLResultType.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

using System.Collections.Generic;
using System;

public sealed record SQuiLResultType<T>
{
	public bool IsValue { get; }
	private T Value { get; } = default!;
	public SQuiLResultType(T value)
	{
		Value = value;
		IsValue = true;
	}

	public bool HasErrors { get; }
	private IReadOnlyList<SQuiLError> Errors { get; } = default!;
	public SQuiLResultType(IReadOnlyList<SQuiLError> errors)
	{
		Errors = errors;
		HasErrors = true;
	}

	public bool TryGetValue(out T value, out IReadOnlyList<SQuiLError> errors)
	{
		value = default!;
		errors = default!;

		if (IsValue)
		{
			value = Value;
			return true;
		}

		errors = Errors;
		return false;
	}
}