//HintName: OwnBeginTranUnderEnabledTransactionErrorsSP0025Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record OwnBeginTranUnderEnabledTransactionErrorsSP0025Response
{
}
