//HintName: CustomTableVariableWithPrimaryConstructorDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class CustomTableVariableWithPrimaryConstructorDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<CustomTableVariableWithPrimaryConstructorResponse>> ProcessCustomTableVariableWithPrimaryConstructorAsync(
		CustomTableVariableWithPrimaryConstructorRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		CustomTableVariableWithPrimaryConstructorResponse response = new();
		
		var isTable = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "tableid:int|isboth:bool|nickname:string":
					{
						isTable = true;
						
						response.Table ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexTableID = reader.GetOrdinal("TableID");
						var indexIsBoth = reader.GetOrdinal("IsBoth");
						var indexNickName = reader.GetOrdinal("NickName");
						
						do
						{
							var valueTableID = reader.GetInt32(indexTableID);
							var valueIsBoth = reader.GetBoolean(indexIsBoth);
							var valueNickName = reader.GetString(indexNickName);
							
							response.Table.Add(new(
								valueTableID,
								valueIsBoth,
								valueNickName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isTable) errors.Add(new(51001, 12, 1, 85, "Table", "Expected return table `Table`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Table table(
			[TableID] int,
			[IsBoth] bit,
			[NickName] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
