//HintName: BinaryListUsesHexConvertDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class BinaryListUsesHexConvertDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessBinaryListUsesHexConvertAsync(
		BinaryListUsesHexConvertRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputBlobs(List<DbParameter> parameters)
		{
			if (request.Blobs is null || request.Blobs.Count == 0) return "";
			
			AddJsonParameter(parameters, "@__json_Params_Blobs", request.Blobs);
			
			return """
			Insert Into @Params_Blobs([BlobID], [Fixed], [Var])
			Select [BlobID], Convert(varbinary(10), [Fixed], 2), Convert(varbinary(max), [Var], 2)
			From OpenJson(@__json_Params_Blobs)
			With (
				[BlobID] int '$.BlobID',
				[Fixed] nvarchar(max) '$.Fixed',
				[Var] nvarchar(max) '$.Var');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Blobs table(
			[BlobID] int,
			[Fixed] binary(10),
			[Var] varbinary(max));
		{inputBlobs(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
