//HintName: SQuiLQueryFilesEnum.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

public enum QueryFiles
{
	TwoContextsWithConflictingNamespace1,
	TwoContextsWithConflictingNamespace2
}
