//HintName: TwoContextsWithConflictingNamespace1Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoContextsWithConflictingNamespace1Response
{
	public System.Collections.Generic.List<TestCase.A.Person>? Person { get; set; }
}
