//HintName: MakeSureErrorTableObjectDoesNotEmitDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;
using System.Data.Common;

using SQuiL;

namespace TestCase;

partial class MakeSureErrorTableObjectDoesNotEmitDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessMakeSureErrorTableObjectDoesNotEmitAsync(
		MakeSureErrorTableObjectDoesNotEmitRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length, EnvironmentName),
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, !request.DebugOnly && (request.Debug || EnvironmentName != "Production"))
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		MakeSureErrorTableObjectDoesNotEmitResponse response = new();
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Error__":
						{
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexNumber = reader.GetOrdinal("Number");
							var indexSeverity = reader.GetOrdinal("Severity");
							var indexState = reader.GetOrdinal("State");
							var indexLine = reader.GetOrdinal("Line");
							var indexProcedure = reader.GetOrdinal("Procedure");
							var indexMessage = reader.GetOrdinal("Message");
							
							do
							{
								if (reader.GetString(0) == "Error")
								{
									var valueNumber = reader.GetInt32(indexNumber);
									var valueSeverity = reader.GetInt32(indexSeverity);
									var valueState = reader.GetInt32(indexState);
									var valueLine = reader.GetInt32(indexLine);
									var valueProcedure = reader.GetString(indexProcedure);
									var valueMessage = reader.GetString(indexMessage);
									
									errors.Add(new(
										valueNumber,
										valueSeverity,
										valueState,
										valueLine,
										valueProcedure,
										valueMessage));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if(errors.Count == 0)
			return SQuiLResultType.Success;
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Error table(
			[__SQuiL__Table__Type__Return_Error__] varchar(max) default('Return_Error'),
			[Number] int,
			[Severity] int,
			[State] int,
			[Line] int,
			[Procedure] varchar(max),
			[Message] varchar(max));
		
		Use [{builder.InitialCatalog}];
		
		Select * From Return_Error;
		
		""";
	}
}
