//HintName: CustomTableVariableWithColumnDefaultDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class CustomTableVariableWithColumnDefaultDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<CustomTableVariableWithColumnDefaultResponse>> ProcessCustomTableVariableWithColumnDefaultAsync(
		CustomTableVariableWithColumnDefaultRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		CustomTableVariableWithColumnDefaultResponse response = new();
		
		var isTable = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "tableid:int|isactive:bool|lastname:string":
					{
						isTable = true;
						
						response.Table ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexTableID = reader.GetOrdinal("TableID");
						var indexIsActive = reader.GetOrdinal("IsActive");
						var indexLastName = reader.GetOrdinal("LastName");
						
						do
						{
							var valueTableID = reader.GetInt32(indexTableID);
							var valueIsActive = reader.GetBoolean(indexIsActive);
							var valueLastName = reader.GetString(indexLastName);
							
							response.Table.Add(new(
								valueTableID,
								valueLastName)
							{
								IsActive = valueIsActive,
							});
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isTable) errors.Add(new(51001, 12, 1, 87, "Table", "Expected return table `Table`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string inputTable(List<DbParameter> parameters)
		{
			if (request.Table is null || request.Table.Count == 0) return "";
			
			var index = 0;
			foreach (var item in request.Table)
			{
				if (item.LastName is not null && item.LastName.Length > 100)
				{
					throw new Exception($"CustomTableVariableWithColumnDefaultRequest Table[{index}].LastName exceeds its maximum length of 100 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Table", request.Table);
			
			return """
			Insert Into @Params_Table([TableID], [IsActive], [LastName])
			Select [TableID], [IsActive], [LastName]
			From OpenJson(@__json_Params_Table)
			With (
				[TableID] int '$.TableID',
				[IsActive] bit '$.IsActive',
				[LastName] varchar(100) '$.LastName');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Table table(
			[TableID] int,
			[IsActive] bit,
			[LastName] varchar(100));
		{inputTable(parameters)}
		
		Declare @Returns_Table table(
			[TableID] int,
			[IsActive] bit,
			[LastName] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
