//HintName: CustomFile.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record CustomFile
{
	public int TableID { get; init; }
	
	public bool IsActive { get; init; } = true;
	
	public string LastName { get; init; }
	
	public CustomFile(
		int tableID,
		string lastName): this()
	{
		TableID = tableID;
		LastName = lastName;
	}
}
