//HintName: TestCase.CustomTableVariableDataContext.CustomTableVariableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record CustomTableVariableResponse
{
	public System.Collections.Generic.List<CustomFile> Table { get; set; } = [];
}
