//HintName: TestCase.SharedTableDataContext.SharedTable2Request.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SharedTable2Request
{
	public bool Debug { get; set; }
}
