//HintName: SharedTable1DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class SharedTableDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<SharedTable1Response>> ProcessSharedTable1Async(
		SharedTable1Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		SharedTable1Response response = new();
		
		var isBob = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Return_Bob__":
						{
							if (isBob) throw new Exception(
								"Already returned value for `Bob`");
							
							isBob = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							if (response.Bob is not null)
								throw new Exception("Bob was already set.");
							
							if (reader.GetString(0) == "Return_Bob")
							{
								response.Bob = new(
									reader.GetInt32(reader.GetOrdinal("ID")));
							}
							else
							{
								continue;
							}
							
							if (await reader.ReadAsync(cancellationToken))
								throw new Exception(
									"Return object results in more than one object. Consider using a return table instead.");
							
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isBob) errors.Add(new(51001, 12, 1, 91, "Bob", "Expected return object `Bob`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Bob table(
			[__SQuiL__Table__Type__Return_Bob__] varchar(max) default('Return_Bob'),
			[ID] int);
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
