//HintName: ThreeLevelInputNestingDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ThreeLevelInputNestingDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessThreeLevelInputNestingAsync(
		ThreeLevelInputNestingRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		List<TestCase.Models.Transcript> __Transcript = [];
		List<TestCase.Models.Institution> __Institution = [];
		List<TestCase.Models.Course> __Course = [];
		
		if (request.Transcript is not null)
		{
			var transcriptKey = __Transcript.Count + 1;
			__Transcript.Add(new(
				transcriptKey,
				request.Transcript.IssueDate));
			foreach (var institution in request.Transcript.Institution ?? [])
			{
				var institutionKey = __Institution.Count + 1;
				__Institution.Add(new(
					institutionKey,
					transcriptKey,
					institution.SchoolName));
				foreach (var course in institution.Course ?? [])
				{
					__Course.Add(new(
						course.CourseID,
						institutionKey,
						course.Title));
				}
			}
		}
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputTranscript(List<DbParameter> parameters)
		{
			AddJsonParameter(parameters, "@__json_Param_Transcript", __Transcript);
			
			return """
			Insert Into @Param_Transcript([TranscriptID], [IssueDate])
			Select [TranscriptID], [IssueDate]
			From OpenJson(@__json_Param_Transcript)
			With (
				[TranscriptID] int '$.TranscriptID',
				[IssueDate] date '$.IssueDate');
			""";
		}
		
		string inputInstitution(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Institution)
			{
				if (item.SchoolName is not null && item.SchoolName.Length > 50)
				{
					throw new Exception($"ThreeLevelInputNestingRequest Institution[{index}].SchoolName exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Institution", __Institution);
			
			return """
			Insert Into @Params_Institution([InstitutionID], [TranscriptID], [SchoolName])
			Select [InstitutionID], [TranscriptID], [SchoolName]
			From OpenJson(@__json_Params_Institution)
			With (
				[InstitutionID] int '$.InstitutionID',
				[TranscriptID] int '$.TranscriptID',
				[SchoolName] varchar(50) '$.SchoolName');
			""";
		}
		
		string inputCourse(List<DbParameter> parameters)
		{
			var index = 0;
			foreach (var item in __Course)
			{
				if (item.Title is not null && item.Title.Length > 50)
				{
					throw new Exception($"ThreeLevelInputNestingRequest Course[{index}].Title exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_Course", __Course);
			
			return """
			Insert Into @Params_Course([CourseID], [InstitutionID], [Title])
			Select [CourseID], [InstitutionID], [Title]
			From OpenJson(@__json_Params_Course)
			With (
				[CourseID] int '$.CourseID',
				[InstitutionID] int '$.InstitutionID',
				[Title] varchar(50) '$.Title');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Param_Transcript table(
			[TranscriptID] int,
			[IssueDate] date);
		{inputTranscript(parameters)}
		
		Declare @Params_Institution table(
			[InstitutionID] int,
			[TranscriptID] int,
			[SchoolName] varchar(50));
		{inputInstitution(parameters)}
		
		Declare @Params_Course table(
			[CourseID] int,
			[InstitutionID] int,
			[Title] varchar(50));
		{inputCourse(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Insert Into dbo.Transcripts Select TranscriptID, IssueDate From @Param_Transcript;
		Insert Into dbo.Institutions Select InstitutionID, TranscriptID, SchoolName From @Params_Institution;
		Insert Into dbo.Courses Select CourseID, InstitutionID, Title From @Params_Course;
		""";
	}
}
