//HintName: TestCase.SharedTableDataContext.SharedTable1DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using SQuiL;

namespace TestCase;

partial class SharedTableDataContext : SQuiLBaseDataContext
{
	public async Task<SharedTable1Response> ProcessSharedTable1Async(
		SharedTable1Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using SqlConnection connection = new(builder.ConnectionString);
		var command = connection.CreateCommand();
		command.CommandText = Query();
		command.Parameters.AddRange(new SqlParameter[]
		{
			new("EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length) { Value = EnvironmentName }, 
			new("Debug", System.Data.SqlDbType.Bit) { Value = EnvironmentName != "Production" }, 
		});
		
		await connection.OpenAsync(cancellationToken);
		
		SharedTable1Response response = new();
		var isBob = false;
		
		using var reader = await command.ExecuteReaderAsync(cancellationToken);
		
		do
		{
			var tableTag = reader.GetName(0);
			if(tableTag.StartsWith("__SQuiL__Table__Type__"))
			{
				switch (tableTag)
				{
					case "__SQuiL__Table__Type__Return_Bob__":
					{
						isBob = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexID = reader.GetOrdinal("ID");
						
						do
						{
							if(reader.GetString(0) == "Return_Bob")
							{
								response.Bob.Add(new(
									reader.GetInt32(indexID)));
							}
						}
						while(await reader.ReadAsync(cancellationToken));
						break;
						
					}
					//default: throw new Exception($"Invalid Table `{reader.GetString(0)}`");
				}
			}
		}
		while (await reader.NextResultAsync(cancellationToken));
		
		if (!isBob) throw new Exception("Expected return table `Bob`)");
		
		return response;
		
		string Query() => $"""
		Declare @Return_Bob table(
			[__SQuiL__Table__Type__Return_Bob__] varchar(max) default('Return_Bob'),
			ID int);
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
