//HintName: TestCase.SharedTableDataContext.SharedTable1Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SharedTable1Response
{
	public System.Collections.Generic.List<Table> Bob { get; set; } = [];
}
