//HintName: MappedTablesWithMismatchedShapes2Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record MappedTablesWithMismatchedShapes2Response
{
	public System.Collections.Generic.List<SharedTable>? Persons { get; set; }
}
