//HintName: MappedTablesWithMismatchedShapes2DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class MappedTablesWithMismatchedShapesDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<MappedTablesWithMismatchedShapes2Response>> ProcessMappedTablesWithMismatchedShapes2Async(
		MappedTablesWithMismatchedShapes2Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		MappedTablesWithMismatchedShapes2Response response = new();
		
		var isPersons = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Error__":
						{
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							break;
						}
						case "__SQuiL__Table__Type__Returns_Persons__":
						{
							isPersons = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexPersonID = reader.GetOrdinal("PersonID");
							var indexLastName = reader.GetOrdinal("LastName");
							
							do
							{
								if (reader.GetString(0) == "Returns_Persons")
								{
									var valuePersonID = reader.GetInt32(indexPersonID);
									var valueLastName = reader.GetString(indexLastName);
									
									response.Persons.Add(new(
										valuePersonID,
										valueLastName));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isPersons) errors.Add(new(51001, 12, 1, 93, "Persons", "Expected return table `Persons`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Persons table(
			[__SQuiL__Table__Type__Returns_Persons__] varchar(max) default('Returns_Persons'),
			[PersonID] int,
			[LastName] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Persons;
		
		""";
	}
}
