//HintName: MappedTablesWithMismatchedShapes1Request.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record MappedTablesWithMismatchedShapes1Request
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
}
