//HintName: MappedTablesWithMismatchedShapes1DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class MappedTablesWithMismatchedShapesDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<MappedTablesWithMismatchedShapes1Response>> ProcessMappedTablesWithMismatchedShapes1Async(
		MappedTablesWithMismatchedShapes1Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length, EnvironmentName),
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, !request.DebugOnly && (request.Debug || EnvironmentName != "Production"))
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		MappedTablesWithMismatchedShapes1Response response = new();
		
		var isPeople = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Error__":
						{
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							break;
						}
						case "__SQuiL__Table__Type__Returns_People__":
						{
							isPeople = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexPersonID = reader.GetOrdinal("PersonID");
							var indexFirstName = reader.GetOrdinal("FirstName");
							
							do
							{
								if (reader.GetString(0) == "Returns_People")
								{
									var valuePersonID = reader.GetInt32(indexPersonID);
									var valueFirstName = reader.GetString(indexFirstName);
									
									response.People.Add(new(
										valuePersonID,
										valueFirstName));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isPeople) errors.Add(new(51001, 12, 1, 95, "People", "Expected return table `People`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_People table(
			[__SQuiL__Table__Type__Returns_People__] varchar(max) default('Returns_People'),
			[PersonID] int,
			[FirstName] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_People;
		
		""";
	}
}
