//HintName: DecimalPrecisionScaleTestResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DecimalPrecisionScaleTestResponse
{
	public System.Collections.Generic.List<TotalsTable>? Totals { get; set; } = [];
}
