//HintName: DecimalPrecisionScaleTestDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class DecimalPrecisionScaleTestDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<DecimalPrecisionScaleTestResponse>> ProcessDecimalPrecisionScaleTestAsync(
		DecimalPrecisionScaleTestRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_Price", System.Data.SqlDbType.Decimal, request.Price ?? (object)System.DBNull.Value
			, p => p.IsNullable = true)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		DecimalPrecisionScaleTestResponse response = new();
		
		var isTotals = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Error__":
						{
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							break;
						}
						case "__SQuiL__Table__Type__Returns_Totals__":
						{
							isTotals = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexTotalID = reader.GetOrdinal("TotalID");
							var indexAmount = reader.GetOrdinal("Amount");
							var indexLabel = reader.GetOrdinal("Label");
							
							do
							{
								if (reader.GetString(0) == "Returns_Totals")
								{
									var valueTotalID = reader.GetInt32(indexTotalID);
									var valueAmount = reader.IsDBNull(indexAmount) ? default! : reader.GetDecimal(indexAmount);
									var valueLabel = reader.GetString(indexLabel);
									
									response.Totals.Add(new(
										valueTotalID,
										valueAmount,
										valueLabel));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isTotals) errors.Add(new(51001, 12, 1, 98, "Totals", "Expected return table `Totals`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string inputCourses(List<DbParameter> parameters)
		{
			System.Text.StringBuilder query = new();
			query.Append("Insert Into @Params_Courses([CourseID], [Credits], [Title])");
			
			if (request.Courses.Count() == 0) return "";
			
			query.AppendLine(" Values");
			
			var comma = "";
			var index = 0;
			
			foreach(var item in request.Courses)
			{
				index++;
				
				query.AppendLine(comma);
				query.Append('(');
				AddParams(query, parameters, index, "ParamsCourses", "CourseID", System.Data.SqlDbType.BigInt, item.CourseID);
				query.Append(", ");
				AddParams(query, parameters, index, "ParamsCourses", "Credits", System.Data.SqlDbType.Decimal, item.Credits);
				query.Append(", ");
				AddParams(query, parameters, index, "ParamsCourses", "Title", System.Data.SqlDbType.VarChar, item.Title, 100);
				query.Append(')');
				
				comma = ",";
			}
			
			query.AppendLine(";");
			query.AppendLine();
			
			return query.ToString();
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Courses table(
			[__SQuiL__Table__Type__Params_Courses__] varchar(max) default('Params_Courses'),
			[CourseID] int,
			[Credits] decimal(10,4),
			[Title] varchar(100));
		{inputCourses(parameters)}
		
		Declare @Returns_Totals table(
			[__SQuiL__Table__Type__Returns_Totals__] varchar(max) default('Returns_Totals'),
			[TotalID] int,
			[Amount] numeric(10, 4) Null,
			[Label] varchar(50));
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
