//HintName: TestCase.PositionalEnabledFalse_NoTransactionInjectedDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class PositionalEnabledFalse_NoTransactionInjectedDataContext : SQuiLBaseDataContext
{
    public PositionalEnabledFalse_NoTransactionInjectedDataContext(IConfiguration Configuration) : base(Configuration) { }
}
