//HintName: PerTypeFidelityRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record PerTypeFidelityRequest
{
	public System.Collections.Generic.List<TestCase.Models.All>? All { get; set; } = [];
}
