//HintName: PerTypeFidelityDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class PerTypeFidelityDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessPerTypeFidelityAsync(
		PerTypeFidelityRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputAll(List<DbParameter> parameters)
		{
			if (request.All is null || request.All.Count == 0) return "";
			
			var index = 0;
			foreach (var item in request.All)
			{
				if (item.Name is not null && item.Name.Length > 100)
				{
					throw new Exception($"PerTypeFidelityRequest All[{index}].Name exceeds its maximum length of 100 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_All", request.All);
			
			return """
			Insert Into @Params_All([Id], [Flag], [Amount], [Ratio], [Name], [WhenDate], [WhenStamp], [WhenOffset], [Key])
			Select [Id], [Flag], [Amount], [Ratio], [Name], [WhenDate], [WhenStamp], [WhenOffset], [Key]
			From OpenJson(@__json_Params_All)
			With (
				[Id] int '$.Id',
				[Flag] bit '$.Flag',
				[Amount] decimal(18,2) '$.Amount',
				[Ratio] float '$.Ratio',
				[Name] varchar(100) '$.Name',
				[WhenDate] date '$.WhenDate',
				[WhenStamp] datetime2 '$.WhenStamp',
				[WhenOffset] datetimeoffset '$.WhenOffset',
				[Key] uniqueidentifier '$.Key');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_All table(
			[Id] int,
			[Flag] bit,
			[Amount] decimal(18,2),
			[Ratio] float,
			[Name] varchar(100),
			[WhenDate] date,
			[WhenStamp] datetime2,
			[WhenOffset] datetimeoffset,
			[Key] uniqueidentifier);
		{inputAll(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
