//HintName: All.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record All(
	int Id,
	bool Flag,
	decimal Amount,
	double Ratio,
	string Name,
	System.DateOnly WhenDate,
	System.DateTime WhenStamp,
	System.DateTimeOffset WhenOffset,
	System.Guid Key);
