//HintName: TestCase.FullVariableDataContext.FullVariableRequestObjectObject.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record FullVariableRequestObjectObject(
	int ObjectID,
	bool IsMale,
	string FirstName);
