//HintName: TestCase.FullVariableDataContext.FullVariableRequestTableTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record FullVariableRequestTableTable(
	int TableID,
	bool IsFemale,
	string LastName);
