//HintName: TestCase.FullVariableDataContext.FullVariableResponseTableTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record FullVariableResponseTableTable(
	int TableID,
	bool IsBoth,
	string NickName);
