//HintName: TestCase.FullVariableDataContext.FullVariableTableTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record FullVariableTableTable(
	int TableID,
	bool IsFemale,
	string LastName,
	bool IsBoth,
	string NickName);
