//HintName: PrimaryKeysNoLinksResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record PrimaryKeysNoLinksResponse
{
	public System.Collections.Generic.List<TestCase.Models.Alpha>? Alpha { get; set; }
	
	public System.Collections.Generic.List<TestCase.Models.Beta>? Beta { get; set; }
}
