//HintName: Enrollment.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Enrollment(
	string Grade)
{
	public TestCase.Models.Student? Student { get; set; }
	public TestCase.Models.Course? Course { get; set; }
}
