<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<RootNamespace>SQuiL</RootNamespace>
		<AssemblyName>SQuiL.SqlServer</AssemblyName>
		<PackageId>SQuiL.SqlServer</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SQuiL.Core\SQuiL.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" />
	</ItemGroup>

</Project>
