//HintName: TestCase.EnabledTransactionWrapsNonQueryPathDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class EnabledTransactionWrapsNonQueryPathDataContext : SQuiLBaseDataContext
{
    public EnabledTransactionWrapsNonQueryPathDataContext(IConfiguration Configuration) : base(Configuration) { }
}
