//HintName: BinaryDataParameterRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record BinaryDataParameterRequest
{
	public byte[] BinaryDataField { get; set; }
	
	public byte[] VarBinaryDataField { get; set; }
}
