//HintName: BinaryDataParameterDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class BinaryDataParameterDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<BinaryDataParameterResponse>> ProcessBinaryDataParameterAsync(
		BinaryDataParameterRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_BinaryDataField", System.Data.SqlDbType.Binary, request.BinaryDataField),
			CreateParameter("@Param_VarBinaryDataField", System.Data.SqlDbType.VarBinary, request.VarBinaryDataField)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		BinaryDataParameterResponse response = new();
		
		var isBinaryTable = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "databinary:byte[]|datavarbinary:byte[]":
					{
						isBinaryTable = true;
						
						response.BinaryTable ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexDataBinary = reader.GetOrdinal("DataBinary");
						var indexDataVarBinary = reader.GetOrdinal("DataVarBinary");
						
						do
						{
							var valueDataBinary = reader.GetFieldValue<byte[]>(indexDataBinary);
							var valueDataVarBinary = reader.GetFieldValue<byte[]>(indexDataVarBinary);
							
							response.BinaryTable.Add(new(
								valueDataBinary,
								valueDataVarBinary));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isBinaryTable) errors.Add(new(51001, 12, 1, 84, "BinaryTable", "Expected return table `BinaryTable`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_BinaryTable table(
			[DataBinary] binary(10),
			[DataVarBinary] varbinary(max));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_BinaryTable
		""";
	}
}
