//HintName: BinaryDataParameterResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record BinaryDataParameterResponse
{
	public System.Collections.Generic.List<BinaryTableTable> BinaryTable { get; set; } = [];
}
