//HintName: TypeKeywordAsColumnNameRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TypeKeywordAsColumnNameRequest
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
}
