//HintName: TypeKeywordAsColumnNameResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TypeKeywordAsColumnNameResponse
{
	public System.Collections.Generic.List<Records>? Records { get; set; }
}
