//HintName: Records.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Records(
	int RecordID,
	System.DateOnly Date,
	System.TimeOnly Time,
	System.DateTime DateTime);
