//HintName: RecordsTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record RecordsTable(
	int RecordID,
	System.DateOnly Date,
	System.TimeOnly Time,
	System.DateTime DateTime);
