//HintName: TypeKeywordAsColumnNameDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class TypeKeywordAsColumnNameDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<TypeKeywordAsColumnNameResponse>> ProcessTypeKeywordAsColumnNameAsync(
		TypeKeywordAsColumnNameRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		TypeKeywordAsColumnNameResponse response = new();
		
		var isRecords = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Error__":
						{
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							break;
						}
						case "__SQuiL__Table__Type__Returns_Records__":
						{
							isRecords = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexRecordID = reader.GetOrdinal("RecordID");
							var indexDate = reader.GetOrdinal("Date");
							var indexTime = reader.GetOrdinal("Time");
							var indexDateTime = reader.GetOrdinal("DateTime");
							
							do
							{
								if (reader.GetString(0) == "Returns_Records")
								{
									var valueRecordID = reader.GetInt32(indexRecordID);
									var valueDate = reader.GetFieldValue<System.DateOnly>(indexDate);
									var valueTime = reader.GetFieldValue<System.TimeOnly>(indexTime);
									var valueDateTime = reader.GetDateTime(indexDateTime);
									
									response.Records.Add(new(
										valueRecordID,
										valueDate,
										valueTime,
										valueDateTime));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isRecords) errors.Add(new(51001, 12, 1, 99, "Records", "Expected return table `Records`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Records table(
			[__SQuiL__Table__Type__Returns_Records__] varchar(max) default('Returns_Records'),
			[RecordID] int,
			[Date] date,
			[Time] time,
			[DateTime] datetime);
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
