//HintName: MultiLineCommentInHeaderRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record MultiLineCommentInHeaderRequest
{
	public int? Count { get; set; }
}
