//HintName: TestCase.BothAttributesDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class BothAttributesDataContext : SQuiLBaseDataContext
{
    public BothAttributesDataContext(IConfiguration Configuration) : base(Configuration) { }
}
