//HintName: TestCase.TwoQueryDataContextDataContext.TwoQueryDataContext1Request.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueryDataContext1Request
{
	public bool Debug { get; set; }
}
