//HintName: SingleObjectUsesOneElementArrayDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class SingleObjectUsesOneElementArrayDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessSingleObjectUsesOneElementArrayAsync(
		SingleObjectUsesOneElementArrayRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputRow(List<DbParameter> parameters)
		{
			if (request.Row is null)
				throw new NullReferenceException(
					"SingleObjectUsesOneElementArrayRequest is missing the required property Row.");
			
			if (request.Row.Name is not null && request.Row.Name.Length > 50)
			{
				throw new Exception($"SingleObjectUsesOneElementArrayRequest table property [Row] has a string property [Name] with more than 50 characters.");
			}
			
			AddJsonParameter(parameters, "@__json_Param_Row", new[] { request.Row });
			
			return """
			Insert Into @Param_Row([RowID], [Name])
			Select [RowID], [Name]
			From OpenJson(@__json_Param_Row)
			With (
				[RowID] int '$.RowID',
				[Name] varchar(50) '$.Name');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Param_Row table(
			[__SQuiL__Table__Type__Param_Row__] varchar(max) default('Param_Row'),
			[RowID] int,
			[Name] varchar(50));
		{inputRow(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
