//HintName: TwoQueryDataContext1DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class TwoQueryDataContextDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType> ProcessTwoQueryDataContext1Async(
		TwoQueryDataContext1Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("ConnectionStringTwoQueryDataContext1");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(SqlException e)
		{
			return new SQuiLResultType(CreateError(e));
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Select 1
		""";
	}
}
