//HintName: Contact.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Contact(
	int ContactID,
	string Name)
{
	public TestCase.Models.Address? Address { get; set; }
}
