//HintName: ChainedEmbedDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

using SQuiL;

namespace TestCase;

partial class ChainedEmbedDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType<ChainedEmbedResponse>> ProcessChainedEmbedAsync(
		ChainedEmbedRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		ChainedEmbedResponse response = new();
		
		var isStructure = false;
		var isContact = false;
		var isAddress = false;
		
		List<SQuiLError> errors = [];
		try
		{
			List<TestCase.Models.Structure> __Structure = [];
			List<int> __Structure__ContactID = [];
			List<TestCase.Models.Contact> __Contact = [];
			List<int> __Contact__AddressID = [];
			List<TestCase.Models.Address> __Address = [];
			
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "title:string|contactid:int":
					{
						isStructure = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexTitle = reader.GetOrdinal("Title");
						var indexContactID = reader.GetOrdinal("ContactID");
						
						do
						{
							var valueTitle = reader.GetString(indexTitle);
							var valueContactID = reader.GetInt32(indexContactID);
							
							__Structure.Add(new(
								valueTitle));
							__Structure__ContactID.Add(valueContactID);
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "contactid:int|name:string|addressid:int":
					{
						isContact = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexContactID = reader.GetOrdinal("ContactID");
						var indexName = reader.GetOrdinal("Name");
						var indexAddressID = reader.GetOrdinal("AddressID");
						
						do
						{
							var valueContactID = reader.GetInt32(indexContactID);
							var valueName = reader.GetString(indexName);
							var valueAddressID = reader.GetInt32(indexAddressID);
							
							__Contact.Add(new(
								valueContactID,
								valueName));
							__Contact__AddressID.Add(valueAddressID);
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "addressid:int|street:string":
					{
						isAddress = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexAddressID = reader.GetOrdinal("AddressID");
						var indexStreet = reader.GetOrdinal("Street");
						
						do
						{
							var valueAddressID = reader.GetInt32(indexAddressID);
							var valueStreet = reader.GetString(indexStreet);
							
							__Address.Add(new(
								valueAddressID,
								valueStreet));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
			
			for (var __i = 0; __i < __Contact.Count; __i++)
			{
				var __fk = __Contact__AddressID[__i];
				var __match = __Address.Where(c => c.AddressID == __fk).ToList();
				if (__match.Count > 1)
				{
					throw new Exception("Lookup `Address` has more than one row for key `AddressID`.");
				}
				__Contact[__i].Address = __match.Count == 1 ? __match[0] : null;
			}
			for (var __i = 0; __i < __Structure.Count; __i++)
			{
				var __fk = __Structure__ContactID[__i];
				var __match = __Contact.Where(c => c.ContactID == __fk).ToList();
				if (__match.Count > 1)
				{
					throw new Exception("Lookup `Contact` has more than one row for key `ContactID`.");
				}
				__Structure[__i].Contact = __match.Count == 1 ? __match[0] : null;
			}
			
			response.Structure = __Structure;
		}
		catch(SqlException e)
		{
			errors.Add(CreateError(e));
		}
		
		if (!isStructure) errors.Add(new(51001, 12, 1, 158, "Structure", "Expected return table `Structure`"));
		if (!isContact) errors.Add(new(51001, 12, 1, 159, "Contact", "Expected return table `Contact`"));
		if (!isAddress) errors.Add(new(51001, 12, 1, 160, "Address", "Expected return table `Address`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Structure table(
			[Title] varchar(50),
			[ContactID] int);
		
		Declare @Returns_Contact table(
			[ContactID] int,
			[Name] varchar(50),
			[AddressID] int);
		
		Declare @Returns_Address table(
			[AddressID] int,
			[Street] varchar(50));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Structure;
		Select * From @Returns_Contact;
		Select * From @Returns_Address;
		""";
	}
}
