//HintName: NullableColumnLengthGuardSkipsNullDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class NullableColumnLengthGuardSkipsNullDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessNullableColumnLengthGuardSkipsNullAsync(
		NullableColumnLengthGuardSkipsNullRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputPeople(List<DbParameter> parameters)
		{
			if (request.People is null || request.People.Count == 0) return "";
			
			var index = 0;
			foreach (var item in request.People)
			{
				if (item.NickName is not null && item.NickName.Length > 50)
				{
					throw new Exception($"NullableColumnLengthGuardSkipsNullRequest People[{index}].NickName exceeds its maximum length of 50 characters.");
				}
				index++;
			}
			
			AddJsonParameter(parameters, "@__json_Params_People", request.People);
			
			return """
			Insert Into @Params_People([PersonID], [NickName])
			Select [PersonID], [NickName]
			From OpenJson(@__json_Params_People)
			With (
				[PersonID] int '$.PersonID',
				[NickName] varchar(50) '$.NickName');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_People table(
			[PersonID] int,
			[NickName] varchar(50) Null);
		{inputPeople(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
