//HintName: NullableColumnLengthGuardSkipsNullRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record NullableColumnLengthGuardSkipsNullRequest
{
	public System.Collections.Generic.List<TestCase.Models.People>? People { get; set; } = [];
}
