//HintName: SameNameTableAndObjectShareOneRecordResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SameNameTableAndObjectShareOneRecordResponse
{
	public System.Collections.Generic.List<TestCase.Models.Person>? Person { get; set; }
}
