//HintName: TransactionAttributeIsEmittedAndContextCompilesRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TransactionAttributeIsEmittedAndContextCompilesRequest
{
	public int Id { get; set; }
}
