//HintName: TransactionAttributeIsEmittedAndContextCompilesResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TransactionAttributeIsEmittedAndContextCompilesResponse
{
}
