//HintName: TestCase.TransactionAttributeIsEmittedAndContextCompilesDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class TransactionAttributeIsEmittedAndContextCompilesDataContext : SqlServerDataContext
{
    public TransactionAttributeIsEmittedAndContextCompilesDataContext(IConfiguration Configuration) : base(Configuration) { }
}
