//HintName: TransactionAttributeIsEmittedAndContextCompilesDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class TransactionAttributeIsEmittedAndContextCompilesDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessTransactionAttributeIsEmittedAndContextCompilesAsync(
		TransactionAttributeIsEmittedAndContextCompilesRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_Id", System.Data.SqlDbType.Int, request.Id)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		using var transaction = connection.BeginTransaction();
		command.Transaction = transaction;
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			transaction.Commit();
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			transaction.Rollback();
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Update [Documents] set Status = 'Done' where Id = @Param_Id;
		""";
	}
}
