//HintName: SmallintKeyInputNestingRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record SmallintKeyInputNestingRequest
{
	public TestCase.Models.Order? Order { get; set; } = default!;
}
