//HintName: Order.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Order(
	short OrderID,
	System.DateOnly Placed)
{
	public System.Collections.Generic.List<TestCase.Models.Line>? Line { get; set; } = [];
}
