//HintName: OutputOnlyQueryGeneratesFullContextResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record OutputOnlyQueryGeneratesFullContextResponse
{
	public long Total { get; set; }
	
	public System.Collections.Generic.List<TestCase.Models.Person>? Person { get; set; }
}
