//HintName: DateTypeVariableDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class DateTypeVariableDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<DateTypeVariableResponse>> ProcessDateTypeVariableAsync(
		DateTypeVariableRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_AsOfDate", System.Data.SqlDbType.Date, request.AsOfDate ?? (object)System.DBNull.Value
			, p => p.IsNullable = true)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		DateTypeVariableResponse response = new();
		
		var isRows = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "rowid:int|dateofbirth:System.DateOnly|birthdate:System.DateOnly":
					{
						isRows = true;
						
						response.Rows ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexRowID = reader.GetOrdinal("RowID");
						var indexDateOfBirth = reader.GetOrdinal("DateOfBirth");
						var indexBirthDate = reader.GetOrdinal("BirthDate");
						
						do
						{
							var valueRowID = reader.GetInt32(indexRowID);
							var valueDateOfBirth = reader.GetFieldValue<System.DateOnly>(indexDateOfBirth);
							var valueBirthDate = reader.GetFieldValue<System.DateOnly>(indexBirthDate);
							
							response.Rows.Add(new(
								valueRowID,
								valueDateOfBirth,
								valueBirthDate));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isRows) errors.Add(new(51001, 12, 1, 87, "Rows", "Expected return table `Rows`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Rows table(
			[RowID] int,
			[DateOfBirth] date,
			[BirthDate] date);
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
