//HintName: DateTypeVariableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DateTypeVariableResponse
{
	public System.Collections.Generic.List<Rows>? Rows { get; set; }
}
