//HintName: DateTypeVariableDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class DateTypeVariableDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<DateTypeVariableResponse>> ProcessDateTypeVariableAsync(
		DateTypeVariableRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_AsOfDate", System.Data.SqlDbType.Date, request.AsOfDate)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		DateTypeVariableResponse response = new();
		
		var isRows = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Returns_Rows__":
						{
							isRows = true;
							
							response.Rows ??= [];
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexRowID = reader.GetOrdinal("RowID");
							var indexDateOfBirth = reader.GetOrdinal("DateOfBirth");
							var indexBirthDate = reader.GetOrdinal("BirthDate");
							
							do
							{
								if (reader.GetString(0) == "Returns_Rows")
								{
									var valueRowID = reader.GetInt32(indexRowID);
									var valueDateOfBirth = reader.GetFieldValue<System.DateOnly>(indexDateOfBirth);
									var valueBirthDate = reader.GetFieldValue<System.DateOnly>(indexBirthDate);
									
									response.Rows.Add(new(
										valueRowID,
										valueDateOfBirth,
										valueBirthDate));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isRows) errors.Add(new(51001, 12, 1, 92, "Rows", "Expected return table `Rows`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Rows table(
			[__SQuiL__Table__Type__Returns_Rows__] varchar(max) default('Returns_Rows'),
			[RowID] int,
			[DateOfBirth] date,
			[BirthDate] date);
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
