//HintName: VarcharMaxColumnEmitsNoLengthGuardRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record VarcharMaxColumnEmitsNoLengthGuardRequest
{
	public System.Collections.Generic.List<TestCase.Models.Rows>? Rows { get; set; } = [];
}
