//HintName: VarcharMaxColumnEmitsNoLengthGuardDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class VarcharMaxColumnEmitsNoLengthGuardDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessVarcharMaxColumnEmitsNoLengthGuardAsync(
		VarcharMaxColumnEmitsNoLengthGuardRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputRows(List<DbParameter> parameters)
		{
			if (request.Rows is null || request.Rows.Count == 0) return "";
			
			AddJsonParameter(parameters, "@__json_Params_Rows", request.Rows);
			
			return """
			Insert Into @Params_Rows([RowID], [Note])
			Select [RowID], [Note]
			From OpenJson(@__json_Params_Rows)
			With (
				[RowID] int '$.RowID',
				[Note] varchar(max) '$.Note');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Rows table(
			[RowID] int,
			[Note] varchar(max));
		{inputRows(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Params_Rows;
		""";
	}
}
