//HintName: ObjectColumnDefaultResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ObjectColumnDefaultResponse
{
	public TestCase.Models.Person? Person { get; set; } = default!;
}
