//HintName: Person.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Person(
	int PersonID,
	int? Score)
{
	public string Note { get; init; } = "hello";
}
