//HintName: DoubleNumberTestRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DoubleNumberTestRequest
{
	public double? Number1 { get; set; }
	
	public double? Number4 { get; set; }
}
