//HintName: DoubleNumberTestDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;
using System.Data.Common;

using SQuiL;

namespace TestCase;

partial class DoubleNumberTestDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessDoubleNumberTestAsync(
		DoubleNumberTestRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length, EnvironmentName),
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, !request.DebugOnly && (request.Debug || EnvironmentName != "Production")),
			CreateParameter("@Param_Number1", System.Data.SqlDbType.Float, request.Number1 ?? (object)System.DBNull.Value
			, p => p.IsNullable = true),
			CreateParameter("@Param_Number4", System.Data.SqlDbType.Float, request.Number4 ?? (object)System.DBNull.Value
			, p => p.IsNullable = true)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Select Param_Number1;
		Select Param_Number4;
		
		""";
	}
}
