//HintName: LengthOnlyDifferenceStillCollidesSP0030Response.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record LengthOnlyDifferenceStillCollidesSP0030Response
{
	public System.Collections.Generic.List<TestCase.Models.A>? A { get; set; }
	
	public System.Collections.Generic.List<TestCase.Models.B>? B { get; set; }
}
