//HintName: EmbeddedLookupInputNullableIntKeyRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record EmbeddedLookupInputNullableIntKeyRequest
{
	public System.Collections.Generic.List<TestCase.Models.Structure>? Structure { get; set; } = [];
}
