//HintName: DoubleNumberTestDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using SQuiL;

namespace TestCase;

partial class DoubleNumberTestDataContext : SQuiLBaseDataContext
{
	public async Task<DoubleNumberTestResponse> ProcessDoubleNumberTestAsync(
		DoubleNumberTestRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using SqlConnection connection = new(builder.ConnectionString);
		var command = connection.CreateCommand();
		
		List<SqlParameter> parameters = new()
		{
			new("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length) { Value = EnvironmentName }, 
			new("@Debug", System.Data.SqlDbType.Bit) { Value = EnvironmentName != "Production" }, 
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		DoubleNumberTestResponse response = new();
		
		var isAnswers = false;
		
		using var reader = await command.ExecuteReaderAsync(cancellationToken);
		
		do
		{
			var tableTag = reader.GetName(0);
			if(tableTag.StartsWith("__SQuiL__Table__Type__"))
			{
				switch (tableTag)
				{
					case "__SQuiL__Table__Type__Error__":
					{
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						break;
					}
					case "__SQuiL__Table__Type__Returns_Answers__":
					{
						isAnswers = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexResponse = reader.GetOrdinal("Response");
						
						do
						{
							if (reader.GetString(0) == "Returns_Answers")
							{
								response.Answers.Add(new(
									reader.GetDouble(indexResponse)));
							}
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
		}
		while (await reader.NextResultAsync(cancellationToken));
		
		if (!isAnswers) throw new Exception("Expected return table `Answers`)");
		
		return response;
		
		string Query(List<SqlParameter> parameters) => $"""
		Declare @Returns_Answers table(
			[__SQuiL__Table__Type__Returns_Answers__] varchar(max) default('Returns_Answers'),
			[Response] float);
		
		Use [{builder.InitialCatalog}];
		
		
		
		""";
	}
}
