//HintName: DoubleNumberTestResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DoubleNumberTestResponse
{
	public System.Collections.Generic.List<AnswersTable> Answers { get; set; } = [];
}
