//HintName: DoubleNumberTestDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class DoubleNumberTestDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<DoubleNumberTestResponse>> ProcessDoubleNumberTestAsync(
		DoubleNumberTestRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		DoubleNumberTestResponse response = new();
		
		var isAnswers = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Returns_Answers__":
						{
							isAnswers = true;
							
							response.Answers ??= [];
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexResponse = reader.GetOrdinal("Response");
							
							do
							{
								if (reader.GetString(0) == "Returns_Answers")
								{
									var valueResponse = reader.GetDouble(indexResponse);
									
									response.Answers.Add(new(
										valueResponse));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isAnswers) errors.Add(new(51001, 12, 1, 85, "Answers", "Expected return table `Answers`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Answers table(
			[__SQuiL__Table__Type__Returns_Answers__] varchar(max) default('Returns_Answers'),
			[Response] float);
		
		Use [{builder.InitialCatalog}];
		
		
		
		""";
	}
}
