//HintName: TestCase.ApplicationSpecificDataContext.QueriesExample.ResponseModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase
{
	public partial record ApplicationSpecificDataContextQueriesExampleResponse()
	{
		public int? Result1 { get; init; }
		public int Result2 { get; init; } = 13;
		public int? That { get; init; }
		public System.Collections.Generic.List<ApplicationSpecificDataContextResponseResult3Table> Result3 { get; init; } = [];
		public System.Collections.Generic.List<ApplicationSpecificDataContextResponseIntegerTable> Integer { get; init; } = [];
		public System.Collections.Generic.List<ApplicationSpecificDataContextResponseResult4Table> Result4 { get; init; } = [];
	}
}
