//HintName: TestCase.QueriesExampleDataContext.QueriesExample.Result4Table.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

public partial record QueriesExampleDataContextQueriesExampleResponseResult4Table(
	int Bob,
	bool Sally);
