//HintName: TestCase.QueriesGetStudentCoursesForEvaluationDataContext.QueriesGetStudentCoursesForEvaluation.PeopleTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record QueriesGetStudentCoursesForEvaluationDataContextQueriesGetStudentCoursesForEvaluationRequestPeopleTable(
	string PersonID);
