//HintName: TestCase.QueriesExampleDataContext.QueriesExample.Result3Table.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

public partial record QueriesExampleDataContextQueriesExampleResponseResult3Table(
	int Bob);
