//HintName: TestCase.QueriesExampleDataContext.QueriesExample.RequestModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record QueriesExampleDataContextQueriesExampleRequest
{
	public System.DateOnly RunAsOf { get; set; } = System.DateOnly.FromDateTime(System.DateTime.Now);
	public string? Bob1 { get; set; }
	public int? Sally1 { get; set; }
	public System.DateOnly? Sally2 { get; set; }
	public string? Bob2 { get; set; }
	public string Bob3 { get; set; } = "";
	public System.Collections.Generic.List<QueriesExampleDataContextQueriesExampleRequestSallyTable> Sally { get; set; } = [];
}
