//HintName: TestCase.QueriesGetStudentCoursesForEvaluationDataContext.QueriesGetStudentCoursesForEvaluation.ResponseModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record QueriesGetStudentCoursesForEvaluationDataContextQueriesGetStudentCoursesForEvaluationResponse
{
}
