//HintName: TestCase.ApplicationSpecificDataContext.QueriesExample.SallyTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

partial record ApplicationSpecificDataContextQueriesExampleRequestSallyTable
{
	string Jim { get; init; }
	
	int Sam { get; init; }
	
	public ApplicationSpecificDataContextQueriesExampleRequestSallyTable(
		bool bob,
		string jim,
		int sam): this()
		{
			Bob = bob;
			Jim = jim;
			Sam = sam;
		}
	}
