//HintName: TestCase.ApplicationSpecificDataContext.QueriesExample.SallyTable.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

public partial record ApplicationSpecificDataContextQueriesExampleRequestSallyTable(
	bool Bob,
	string Jim,
	int Sam);
