//HintName: TestCase.ApplicationSpecificDataContext.QueriesGetStudentCoursesForEvaluation.RequestModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase
{
	public partial record ApplicationSpecificDataContextQueriesGetStudentCoursesForEvaluationRequest()
	{
		public System.DateOnly RunAsOf { get; init; } = '2008-10-01';
		public bool Debug { get; init; }
		public bool Development { get; init; }
		public System.Collections.Generic.List<ApplicationSpecificDataContextRequestPeopleTable> People { get; init; } = [];
	}
}
