//HintName: SQuiLAttribute.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
public class SQuiLAttribute : System.Attribute
{
	public QueryFiles Type { get; }

	public string Setting { get; }

	public SQuiLAttribute(
		QueryFiles type,
		string setting = "SQuiLDatabase")
	{
		Type = type;
		Setting = setting;
	}
}