//HintName: TestCase.TwoQueryDataContextDataContext.TwoQueryDataContext1.RequestModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record TwoQueryDataContextDataContextTwoQueryDataContext1Request
{
	public bool Debug { get; set; }
}
