//HintName: TestCase.ApplicationSpecificDataContext.QueriesExample.Result3Table.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

public partial record ApplicationSpecificDataContextQueriesExampleResponseResult3Table(
	int Bob);
