//HintName: TestCase.ApplicationSpecificDataContext.QueriesExample.IntegerTable.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

public partial record ApplicationSpecificDataContextQueriesExampleResponseIntegerTable(
	int Bob);
