//HintName: TestCase.ApplicationSpecificDataContext.QueriesGetStudentCoursesForEvaluation.PeopleTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ApplicationSpecificDataContextQueriesGetStudentCoursesForEvaluationRequestPeopleTable(
	string PersonID);
