//HintName: TestCase.QueriesExampleDataContext.QueriesExample.SallyTable.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

public partial record QueriesExampleDataContextQueriesExampleRequestSallyTable(
	bool Bob,
	string Jim,
	int Sam);
