//HintName: TestCase.QueriesExampleDataContext.QueriesExample.IntegerTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record QueriesExampleDataContextQueriesExampleResponseIntegerTable(
	int Bob);
