//HintName: TestCase.ApplicationSpecificDataContext.QueriesExample.RequestModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

partial record ApplicationSpecificDataContextQueriesExampleRequest
{
	public System.DateOnly RunAsOf { get; set; } = System.DateOnly.FromDateTime(System.DateTime.Now);
	public string Bob3 { get; set; } = "";
	public System.Collections.Generic.List<ApplicationSpecificDataContextQueriesExampleRequestSallyTable> Sally { get; set; } = [];
}
