//HintName: TestCase.QueriesExampleDataContext.QueriesExample.RequestModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase
{
	public partial record QueriesExampleDataContextQueriesExampleRequest()
	{
		public System.DateOnly RunAsOf { get; init; } = System.DateOnly.FromDateTime(System.DateTime.Now);
		public string? Bob1 { get; init; }
		public int? Sally1 { get; init; }
		public System.DateOnly? Sally2 { get; init; }
		public string? Bob2 { get; init; }
		public string Bob3 { get; init; } = "";
		public System.Collections.Generic.List<QueriesExampleDataContextRequestSallyTable> Sally { get; init; } = [];
	}
}
