//HintName: TestCase.ApplicationSpecificDataContext.QueriesExample.Result4Table.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ApplicationSpecificDataContextQueriesExampleResponseResult4Table(
	int Bob,
	bool Sally);
