//HintName: TestCase.CustomSettingNameDataContext.CustomSettingName.ResponseModel.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record CustomSettingNameDataContextCustomSettingNameResponse
{
}
