//HintName: SQuiLBaseDataContext.g.cs
// <auto-generated />

#nullable enable

namespace SQuiL;

using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Data.Common;

public abstract partial class SQuiLBaseDataContext(IConfiguration Configuration)
{
	//public virtual string SettingName { get; } = "SQuiLDatabase";

	protected string EnvironmentName { get; } = Configuration.GetSection("EnvironmentName")?.Value
		?? Environment.GetEnvironmentVariable(Configuration.GetSection("EnvironmentVariable")?.Value ?? "ASPNETCORE_ENVIRONMENT")
		?? "Development";

	protected SqlConnectionStringBuilder ConnectionStringBuilder(string settingName)
	{
		return new SqlConnectionStringBuilder(Configuration.GetConnectionString(settingName)
			?? throw new Exception($"Cannot find a connection string in the appsettings for {settingName}."));
	}
	
	public virtual System.Data.Common.DbConnection CreateConnection(string connectionString) => new SqlConnection(connectionString);

	public virtual System.Data.Common.DbParameter CreateParameter(string name, System.Data.SqlDbType type, object value) => new SqlParameter(name, type) { Value = value };

	public virtual System.Data.Common.DbParameter CreateParameter(string name, System.Data.SqlDbType type, object value, Action<System.Data.Common.DbParameter>? callback)
	{
		var parameter = CreateParameter(name, type, value);
		callback?.Invoke(parameter);
		return parameter;
	}

	public virtual System.Data.Common.DbParameter CreateParameter(string name, System.Data.SqlDbType type, int size, object value) => CreateParameter(name, type, size, value, default);

	public virtual System.Data.Common.DbParameter CreateParameter(string name, System.Data.SqlDbType type, int size, object value, Action<System.Data.Common.DbParameter>? callback)
	{
		var parameter = CreateParameter(name, type, value);
		parameter.Size = size;
		callback?.Invoke(parameter);
		return parameter;
	}

	protected void AddParams(System.Text.StringBuilder query, List<DbParameter> parameters, int index, string table, string name, System.Data.SqlDbType type, object value, int size = 0)
	{
		var parameter = $"@{table}_{index}_{name}";
		query.Append(parameter);

		var variable = CreateParameter(parameter, type, value);

		if (size > 0)
		{
			variable.Size = size;
			variable.Value = value is null || ((string)value).Length <= size
				? (value ?? "Null")
				: throw new Exception($"""
					ParamsTable model table property at index [{index}] has a string property [{name}]
					with more than {size} characters.
					""");
		}

		parameters.Add(variable);
	}
}