//HintName: ImageColumnUsesHexConvertRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ImageColumnUsesHexConvertRequest
{
	public System.Collections.Generic.List<TestCase.Models.Blobs>? Blobs { get; set; } = [];
}
