//HintName: ImageColumnUsesHexConvertDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ImageColumnUsesHexConvertDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessImageColumnUsesHexConvertAsync(
		ImageColumnUsesHexConvertRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string inputBlobs(List<DbParameter> parameters)
		{
			if (request.Blobs is null || request.Blobs.Count == 0) return "";
			
			AddJsonParameter(parameters, "@__json_Params_Blobs", request.Blobs);
			
			return """
			Insert Into @Params_Blobs([ID], [Data])
			Select [ID], Convert(varbinary(max), [Data], 2)
			From OpenJson(@__json_Params_Blobs)
			With (
				[ID] int '$.ID',
				[Data] nvarchar(max) '$.Data');
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Params_Blobs table(
			[ID] int,
			[Data] image);
		{inputBlobs(parameters)}
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Params_Blobs;
		""";
	}
}
