//HintName: TestCase.SecondDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class SecondDataContext : SQuiLBaseDataContext
{
    public SecondDataContext(IConfiguration Configuration) : base(Configuration) { }
}
