//HintName: SameQueryFileOnTwoContextsIsErrorDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class FirstDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType> ProcessSameQueryFileOnTwoContextsIsErrorAsync(
		SameQueryFileOnTwoContextsIsErrorRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(Microsoft.Data.SqlClient.SqlException e)
		{
			return new SQuiLResultType(new SQuiLError(e));
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
