//HintName: TestCase.FirstDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class FirstDataContext : SQuiLBaseDataContext
{
    public FirstDataContext(IConfiguration Configuration) : base(Configuration) { }
}
