//HintName: MoneyTypesMapToDecimalDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class MoneyTypesMapToDecimalDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType> ProcessMoneyTypesMapToDecimalAsync(
		MoneyTypesMapToDecimalRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_Price", System.Data.SqlDbType.Money, request.Price),
			CreateParameter("@Param_Fee", System.Data.SqlDbType.SmallMoney, request.Fee)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(SqlException e)
		{
			return new SQuiLResultType(CreateError(e));
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Select @Param_Price, @Param_Fee;
		""";
	}
}
