//HintName: MoneyTypesMapToDecimalRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record MoneyTypesMapToDecimalRequest
{
	public decimal Price { get; set; }
	
	public decimal Fee { get; set; }
}
