//HintName: ManyToManyJunctionDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

using SQuiL;

namespace TestCase;

partial class ManyToManyJunctionDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType<ManyToManyJunctionResponse>> ProcessManyToManyJunctionAsync(
		ManyToManyJunctionRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		ManyToManyJunctionResponse response = new();
		
		var isStudent = false;
		var isCourse = false;
		var isEnrollment = false;
		
		List<SQuiLError> errors = [];
		try
		{
			List<TestCase.Models.Student> __Student = [];
			List<TestCase.Models.Course> __Course = [];
			List<TestCase.Models.Enrollment> __Enrollment = [];
			List<int> __Enrollment__CourseID = [];
			
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "studentid:int|name:string":
					{
						isStudent = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexStudentID = reader.GetOrdinal("StudentID");
						var indexName = reader.GetOrdinal("Name");
						
						do
						{
							var valueStudentID = reader.GetInt32(indexStudentID);
							var valueName = reader.GetString(indexName);
							
							__Student.Add(new(
								valueStudentID,
								valueName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "courseid:int|title:string":
					{
						isCourse = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexCourseID = reader.GetOrdinal("CourseID");
						var indexTitle = reader.GetOrdinal("Title");
						
						do
						{
							var valueCourseID = reader.GetInt32(indexCourseID);
							var valueTitle = reader.GetString(indexTitle);
							
							__Course.Add(new(
								valueCourseID,
								valueTitle));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "studentid:int|courseid:int|grade:string":
					{
						isEnrollment = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexStudentID = reader.GetOrdinal("StudentID");
						var indexCourseID = reader.GetOrdinal("CourseID");
						var indexGrade = reader.GetOrdinal("Grade");
						
						do
						{
							var valueStudentID = reader.GetInt32(indexStudentID);
							var valueCourseID = reader.GetInt32(indexCourseID);
							var valueGrade = reader.GetString(indexGrade);
							
							__Enrollment.Add(new(
								valueStudentID,
								valueGrade));
							__Enrollment__CourseID.Add(valueCourseID);
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
			
			for (var __i = 0; __i < __Enrollment.Count; __i++)
			{
				var __fk = __Enrollment__CourseID[__i];
				var __match = __Course.Where(c => c.CourseID == __fk).ToList();
				if (__match.Count > 1)
				{
					throw new Exception("Lookup `Course` has more than one row for key `CourseID`.");
				}
				__Enrollment[__i].Course = __match.Count == 1 ? __match[0] : null;
			}
			foreach (var parent in __Student)
			{
				parent.Enrollment = __Enrollment.Where(c => c.StudentID == parent.StudentID).ToList();
			}
			
			response.Student = __Student;
		}
		catch(SqlException e)
		{
			errors.Add(CreateError(e));
		}
		
		if (!isStudent) errors.Add(new(51001, 12, 1, 151, "Student", "Expected return table `Student`"));
		if (!isCourse) errors.Add(new(51001, 12, 1, 152, "Course", "Expected return table `Course`"));
		if (!isEnrollment) errors.Add(new(51001, 12, 1, 153, "Enrollment", "Expected return table `Enrollment`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Student table(
			[StudentID] int,
			[Name] varchar(50));
		
		Declare @Returns_Course table(
			[CourseID] int,
			[Title] varchar(50));
		
		Declare @Returns_Enrollment table(
			[StudentID] int,
			[CourseID] int,
			[Grade] varchar(2));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Student;
		Select * From @Returns_Course;
		Select * From @Returns_Enrollment;
		""";
	}
}
