//HintName: Student.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Student(
	int StudentID,
	string Name)
{
	public System.Collections.Generic.List<TestCase.Models.Enrollment>? Enrollment { get; set; }
}
