/**
 * SQuiL C# Preview Generator
 *
 * Produces a human-readable approximation of what the SQuiL source generator
 * would emit for a given .squil file.  This is intentionally a preview — it
 * does not attempt to replicate every nuance of the real generator.
 */

import { SQuiLParseResult, SQuiLVariable } from './parser';

// ─── SQL → C# type mapping ────────────────────────────────────────────────

const SQL_TO_CS: Record<string, string> = {
  bigint: 'long',
  binary: 'byte[]',
  bit: 'bool',
  char: 'string',
  date: 'DateOnly',
  datetime: 'DateTime',
  datetime2: 'DateTime',
  datetimeoffset: 'DateTimeOffset',
  decimal: 'decimal',
  float: 'double',
  image: 'byte[]',
  int: 'int',
  money: 'decimal',
  nchar: 'string',
  ntext: 'string',
  numeric: 'decimal',
  nvarchar: 'string',
  real: 'float',
  smalldatetime: 'DateTime',
  smallint: 'short',
  smallmoney: 'decimal',
  text: 'string',
  time: 'TimeSpan',
  timestamp: 'byte[]',
  tinyint: 'byte',
  uniqueidentifier: 'Guid',
  varbinary: 'byte[]',
  varchar: 'string',
  xml: 'string',
};

export function sqlToCSharp(sqlType: string): string {
  const base = sqlType.toLowerCase().replace(/\s*\(.*\)/, '').trim();
  return SQL_TO_CS[base] ?? 'object';
}

/**
 * Record-type name SQuiL generates for a table/object variable.
 * The Table/Object suffix was dropped in TODO #3 — the bare name is used directly.
 */
function recordTypeName(v: SQuiLVariable): string {
  return v.name;
}

function isCollectionRole(v: SQuiLVariable): boolean {
  return v.role === 'params' || v.role === 'returns';
}

function getPropertyType(v: SQuiLVariable, modelsNs?: string): string {
  if (v.role === 'params' || v.role === 'returns') {
    const typeName = modelsNs ? `${modelsNs}.${recordTypeName(v)}` : recordTypeName(v);
    return `List<${typeName}>?`;
  }
  if (v.role === 'param-table' || v.role === 'return-table') {
    const typeName = modelsNs ? `${modelsNs}.${recordTypeName(v)}` : recordTypeName(v);
    return `${typeName}?`;
  }
  // Scalars: non-nullable unless an explicit `null` marker was declared. Ref types are NOT auto-?.
  const cs = sqlToCSharp(v.sqlType);
  return v.nullable ? `${cs}?` : cs;
}

// ─── Main entry point ─────────────────────────────────────────────────────

export function generateCSharpPreview(
  parsed: SQuiLParseResult,
  queryName: string,
  namespace = 'YourNamespace',
): string {
  const db = parsed.database ?? '/* database */';
  const lines: string[] = [];

  const params = parsed.variables.filter(v =>
    v.role === 'param' || v.role === 'params' || v.role === 'param-table',
  );
  const returns = parsed.variables.filter(v =>
    v.role === 'return' || v.role === 'returns' || v.role === 'return-table',
  );

  // Collect all table-valued variables that need row records
  const tableVars = [
    ...params.filter(v => v.columns && v.columns.length > 0),
    ...returns.filter(v => v.columns && v.columns.length > 0),
  ];
  const modelsNs = `${namespace}.Models`;

  banner(lines, queryName, db);
  lines.push('');
  lines.push(`namespace ${namespace};`);
  lines.push('');

  // ── Enum entry hint
  lines.push(`// ── QueryFiles enum entry ────────────────────────────────`);
  lines.push(`// Generated by SQuiL.SourceGenerator — do not edit manually.`);
  lines.push(`// Your QueryFiles enum will include:`);
  lines.push(`//   public enum QueryFiles { ..., ${queryName} }`);
  lines.push('');

  // ── using for the Models sub-namespace (only when row records exist)
  if (tableVars.length > 0) {
    lines.push(`using ${modelsNs};`);
    lines.push('');
  }

  // ── Request record (always partial; specials are opt-in)
  lines.push(`// ── Request ─────────────────────────────────────────────`);
  emitModelRecord(lines, `${queryName}Request`, params, /*isResponse*/ false, parsed.variables, modelsNs);

  // ── Response record
  if (returns.length > 0) {
    lines.push(`// ── Response ────────────────────────────────────────────`);
    emitModelRecord(lines, `${queryName}Response`, returns, /*isResponse*/ true, undefined, modelsNs);
  }

  // ── Data context
  lines.push(`// ── DataContext ─────────────────────────────────────────`);
  lines.push(`// SQuiL emits this method into your partial class. You may omit the`);
  lines.push(`// base type and constructor — SQuiL supplies both when absent:`);
  lines.push(`//   public partial class ${queryName}DataContext { }`);
  lines.push(`// (Add your own constructor to customize; it must call : base(configuration).)`);
  lines.push('');

  const responseType = returns.length === 0
    ? 'SQuiLResultType'
    : `SQuiLResultType<${queryName}Response>`;

  lines.push(`public async Task<${responseType}> Process${queryName}Async(`);
  lines.push(`    ${queryName}Request request,`);
  lines.push(`    CancellationToken cancellationToken = default!)`);
  lines.push(`{`);
  lines.push(`    /* generated body */`);
  lines.push(`}`);
  lines.push('');

  // ── DI extension hint
  lines.push(`// ── Dependency Injection ────────────────────────────────`);
  lines.push(`// SQuiL emits an AddSQuiL extension that registers every data context:`);
  lines.push(`//`);
  lines.push(`//   builder.AddSQuiL();`);
  lines.push(`//`);
  lines.push(`// Connection string key: "ConnectionStrings:${db}"`);

  // ── Row records emitted into the .Models sub-namespace
  if (tableVars.length > 0) {
    lines.push('');
    lines.push(`// ── Row records ─────────────────────────────────────────`);
    lines.push(`// Row records live in the .Models sub-namespace, mirroring the generator.`);
    lines.push(`namespace ${modelsNs};`);
    lines.push('');
    for (const v of tableVars) {
      emitTableRecord(lines, recordTypeName(v), v);
    }
  }

  return lines.join('\n');
}

// ─── Helpers ─────────────────────────────────────────────────────────────

function banner(lines: string[], queryName: string, db: string): void {
  lines.push(`// ╔═══════════════════════════════════════════════════════╗`);
  lines.push(`// ║  SQuiL Generated C# Preview                          ║`);
  lines.push(`// ╠═══════════════════════════════════════════════════════╣`);
  lines.push(`// ║  Query    : ${pad(queryName, 41)}║`);
  lines.push(`// ║  Database : ${pad(db, 41)}║`);
  lines.push(`// ╠═══════════════════════════════════════════════════════╣`);
  lines.push(`// ║  ⚠  This is a PREVIEW only.                          ║`);
  lines.push(`// ║     Actual code is emitted by SQuiL.SourceGenerator  ║`);
  lines.push(`// ║     when you run  dotnet build.                       ║`);
  lines.push(`// ╚═══════════════════════════════════════════════════════╝`);
}

function pad(s: string, len: number): string {
  return s.length >= len ? s.substring(0, len) : s + ' '.repeat(len - s.length);
}

/**
 * Approximates the generator's per-type default initializer for a column
 * `DEFAULT <raw>`: decimal gets an `m` suffix, single-quoted SQL strings become
 * double-quoted C#, everything else is emitted as-is (date/guid are approximate
 * in the preview — the real generator wraps them in a Parse call).
 */
function csharpDefault(sqlType: string, raw: string): string {
  if (raw.startsWith("'") && raw.endsWith("'")) return `"${raw.slice(1, -1)}"`;
  const base = sqlType.toLowerCase().replace(/\s*\(.*\)/, '').trim();
  if (base === 'decimal' || base === 'numeric' || base === 'money' || base === 'smallmoney') return `${raw}m`;
  return raw;
}

function emitTableRecord(lines: string[], typeName: string, v: SQuiLVariable): void {
  if (!v.columns || v.columns.length === 0) return;

  const csType = (col: typeof v.columns[number]): string => {
    const cs = sqlToCSharp(col.sqlType);
    return col.nullable ? `${cs}?` : cs;
  };

  const positional = v.columns.filter(c => !c.defaultValue);
  const defaulted = v.columns.filter(c => c.defaultValue);
  const params = positional.map(c => `${csType(c)} ${c.name}`).join(', ');

  if (defaulted.length === 0) {
    lines.push(`public partial record ${typeName}(${params});`);
    lines.push('');
    return;
  }

  lines.push(`public partial record ${typeName}(${params})`);
  lines.push(`{`);
  defaulted.forEach(col => {
    lines.push(`    public ${csType(col)} ${col.name} { get; init; } = ${csharpDefault(col.sqlType, col.defaultValue!)};`);
  });
  lines.push(`}`);
  lines.push('');
}

function emitModelRecord(
  lines: string[],
  typeName: string,
  vars: SQuiLVariable[],
  isResponse: boolean,
  allVars?: SQuiLVariable[],
  modelsNs?: string,
): void {
  lines.push(`public partial record ${typeName}`);
  lines.push(`{`);

  // *Request specials are OPT-IN — each appears only when its bare special is
  // declared in the SQL header. `@Debug` → `bool Debug`, `@SuppressDebug` →
  // `bool SuppressDebug` (replaces the old always-on `DebugOnly`), `@AsOfDate`
  // → a nullable typed property. `@EnvironmentName` is a sent parameter only,
  // never a property.
  if (!isResponse) {
    const declared = allVars ?? [];
    const hasDebug = declared.some(v => v.role === 'debug');
    const hasSuppressDebug = declared.some(v => v.role === 'suppressDebug');
    const asOfDate = declared.find(v => v.role === 'asOfDate');

    if (hasDebug) lines.push(`    public bool Debug { get; set; }`);
    if (hasSuppressDebug) lines.push(`    public bool SuppressDebug { get; set; }`);
    if (asOfDate) {
      // Take only the type token (drop any "= default" the SQL initializer adds),
      // matching the generator which maps the bare declared type. AsOfDate is
      // always nullable on *Request.
      const asOfType = asOfDate.sqlType.split(/[\s=]/)[0];
      lines.push(`    public ${sqlToCSharp(asOfType)}? AsOfDate { get; set; }`);
    }

    if ((hasDebug || hasSuppressDebug || asOfDate) && vars.length > 0) lines.push('');
  }

  vars.forEach(v => {
    const initializer = (!isResponse && isCollectionRole(v)) ? ' = []' : '';
    lines.push(`    public ${getPropertyType(v, modelsNs)} ${v.name} { get; set; }${initializer};`);
  });

  lines.push(`}`);
  lines.push('');
}
