/**
 * SQuiL C# Preview Generator
 *
 * Produces a human-readable approximation of what the SQuiL source generator
 * would emit for a given .squil file.  This is intentionally a preview — it
 * does not attempt to replicate every nuance of the real generator.
 */

import { SQuiLParseResult, SQuiLVariable } from './parser';

// ─── SQL → C# type mapping ────────────────────────────────────────────────

const SQL_TO_CS: Record<string, string> = {
  bigint: 'long',
  binary: 'byte[]',
  bit: 'bool',
  char: 'string',
  date: 'DateOnly',
  datetime: 'DateTime',
  datetime2: 'DateTime',
  datetimeoffset: 'DateTime',   // SQuiL converts datetimeoffset → DateTime
  decimal: 'decimal',
  float: 'double',
  image: 'byte[]',
  int: 'int',
  money: 'decimal',
  nchar: 'string',
  ntext: 'string',
  numeric: 'decimal',
  nvarchar: 'string',
  real: 'float',
  smalldatetime: 'DateTime',
  smallint: 'short',
  smallmoney: 'decimal',
  text: 'string',
  time: 'TimeSpan',
  timestamp: 'byte[]',
  tinyint: 'byte',
  uniqueidentifier: 'Guid',
  varbinary: 'byte[]',
  varchar: 'string',
  xml: 'string',
};

function sqlToCSharp(sqlType: string): string {
  const base = sqlType.toLowerCase().replace(/\s*\(.*\)/, '').trim();
  return SQL_TO_CS[base] ?? 'object';
}

/**
 * Record-type name SQuiL generates for a table/object variable:
 *   - role 'params' / 'returns'           → `<Name>Table`  (collection element)
 *   - role 'param-table' / 'return-table' → `<Name>Object` (single object)
 */
function recordTypeName(v: SQuiLVariable): string {
  if (v.role === 'params' || v.role === 'returns') return `${v.name}Table`;
  if (v.role === 'param-table' || v.role === 'return-table') return `${v.name}Object`;
  return v.name;
}

function getPropertyType(v: SQuiLVariable): string {
  if (v.role === 'params' || v.role === 'returns') {
    return `List<${recordTypeName(v)}>?`;
  }
  if (v.role === 'param-table' || v.role === 'return-table') {
    return `${recordTypeName(v)}?`;
  }
  // Scalars: nullable for reference types and explicit-nullable; non-nullable value types stay as-is.
  const cs = sqlToCSharp(v.sqlType);
  const isRefType = cs === 'string' || cs === 'byte[]';
  return isRefType ? `${cs}?` : cs;
}

function isCollectionRole(v: SQuiLVariable): boolean {
  return v.role === 'params' || v.role === 'returns';
}

// ─── Main entry point ─────────────────────────────────────────────────────

export function generateCSharpPreview(
  parsed: SQuiLParseResult,
  queryName: string,
  namespace = 'YourNamespace',
): string {
  const db = parsed.database ?? '/* database */';
  const lines: string[] = [];

  const params = parsed.variables.filter(v =>
    v.role === 'param' || v.role === 'params' || v.role === 'param-table',
  );
  const returns = parsed.variables.filter(v =>
    v.role === 'return' || v.role === 'returns' || v.role === 'return-table',
  );

  banner(lines, queryName, db);
  lines.push('');
  lines.push(`namespace ${namespace};`);
  lines.push('');

  // ── Enum entry hint
  lines.push(`// ── QueryFiles enum entry ────────────────────────────────`);
  lines.push(`// Generated by SQuiL.SourceGenerator — do not edit manually.`);
  lines.push(`// Your QueryFiles enum will include:`);
  lines.push(`//   public enum QueryFiles { ..., ${queryName} }`);
  lines.push('');

  // ── Table-row records (input side)
  for (const v of params) {
    if (v.columns && v.columns.length > 0) {
      emitTableRecord(lines, recordTypeName(v), v);
    }
  }

  // ── Request record (always partial; specials are opt-in)
  lines.push(`// ── Request ─────────────────────────────────────────────`);
  emitModelRecord(lines, `${queryName}Request`, params, /*isResponse*/ false, parsed.variables);

  // ── Table-row records (output side)
  for (const v of returns) {
    if (v.columns && v.columns.length > 0) {
      emitTableRecord(lines, recordTypeName(v), v);
    }
  }

  // ── Response record
  if (returns.length > 0) {
    lines.push(`// ── Response ────────────────────────────────────────────`);
    emitModelRecord(lines, `${queryName}Response`, returns, /*isResponse*/ true);
  }

  // ── Data context
  lines.push(`// ── DataContext ─────────────────────────────────────────`);
  lines.push(`// SQuiL emits this method into your partial class:`);
  lines.push(`//   public partial class ${queryName}DataContext(IConfiguration configuration)`);
  lines.push(`//       : SQuiLBaseDataContext(configuration);`);
  lines.push('');

  const responseType = returns.length === 0
    ? 'SQuiLResultType'
    : `SQuiLResultType<${queryName}Response>`;

  lines.push(`public async Task<${responseType}> Process${queryName}Async(`);
  lines.push(`    ${queryName}Request request,`);
  lines.push(`    CancellationToken cancellationToken = default!)`);
  lines.push(`{`);
  lines.push(`    /* generated body */`);
  lines.push(`}`);
  lines.push('');

  // ── DI extension hint
  lines.push(`// ── Dependency Injection ────────────────────────────────`);
  lines.push(`// SQuiL emits an AddSQuiL extension that registers every data context:`);
  lines.push(`//`);
  lines.push(`//   builder.AddSQuiL();`);
  lines.push(`//`);
  lines.push(`// Connection string key: "ConnectionStrings:${db}"`);

  return lines.join('\n');
}

// ─── Helpers ─────────────────────────────────────────────────────────────

function banner(lines: string[], queryName: string, db: string): void {
  lines.push(`// ╔═══════════════════════════════════════════════════════╗`);
  lines.push(`// ║  SQuiL Generated C# Preview                          ║`);
  lines.push(`// ╠═══════════════════════════════════════════════════════╣`);
  lines.push(`// ║  Query    : ${pad(queryName, 41)}║`);
  lines.push(`// ║  Database : ${pad(db, 41)}║`);
  lines.push(`// ╠═══════════════════════════════════════════════════════╣`);
  lines.push(`// ║  ⚠  This is a PREVIEW only.                          ║`);
  lines.push(`// ║     Actual code is emitted by SQuiL.SourceGenerator  ║`);
  lines.push(`// ║     when you run  dotnet build.                       ║`);
  lines.push(`// ╚═══════════════════════════════════════════════════════╝`);
}

function pad(s: string, len: number): string {
  return s.length >= len ? s.substring(0, len) : s + ' '.repeat(len - s.length);
}

function emitTableRecord(lines: string[], typeName: string, v: SQuiLVariable): void {
  if (!v.columns || v.columns.length === 0) return;
  lines.push(`public partial record ${typeName}`);
  lines.push(`{`);
  v.columns.forEach(col => {
    const cs = sqlToCSharp(col.sqlType);
    const isRefType = cs === 'string' || cs === 'byte[]';
    const csType = isRefType || col.nullable ? `${cs}?` : cs;
    lines.push(`    public ${csType} ${col.name} { get; set; }`);
  });
  lines.push(`}`);
  lines.push('');
}

function emitModelRecord(
  lines: string[],
  typeName: string,
  vars: SQuiLVariable[],
  isResponse: boolean,
  allVars?: SQuiLVariable[],
): void {
  lines.push(`public partial record ${typeName}`);
  lines.push(`{`);

  // *Request specials are OPT-IN — each appears only when its bare special is
  // declared in the SQL header. `@Debug` → `bool Debug`, `@SuppressDebug` →
  // `bool SuppressDebug` (replaces the old always-on `DebugOnly`), `@AsOfDate`
  // → a nullable typed property. `@EnvironmentName` is a sent parameter only,
  // never a property.
  if (!isResponse) {
    const declared = allVars ?? [];
    const hasDebug = declared.some(v => v.role === 'debug');
    const hasSuppressDebug = declared.some(v => v.role === 'suppressDebug');
    const asOfDate = declared.find(v => v.role === 'asOfDate');

    if (hasDebug) lines.push(`    public bool Debug { get; set; }`);
    if (hasSuppressDebug) lines.push(`    public bool SuppressDebug { get; set; }`);
    if (asOfDate) {
      // Take only the type token (drop any "= default" the SQL initializer adds),
      // matching the generator which maps the bare declared type. AsOfDate is
      // always nullable on *Request.
      const asOfType = asOfDate.sqlType.split(/[\s=]/)[0];
      lines.push(`    public ${sqlToCSharp(asOfType)}? AsOfDate { get; set; }`);
    }

    if ((hasDebug || hasSuppressDebug || asOfDate) && vars.length > 0) lines.push('');
  }

  vars.forEach(v => {
    const type = getPropertyType(v);
    const initializer = isCollectionRole(v) ? ' = []' : '';
    lines.push(`    public ${type} ${v.name} { get; set; }${initializer};`);
  });

  lines.push(`}`);
  lines.push('');
}
