//HintName: ThreeLevelListNestingResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ThreeLevelListNestingResponse
{
	public TestCase.Models.Transcript? Transcript { get; set; } = default!;
}
