//HintName: BareScalarSelectGetsImplicitAliasResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record BareScalarSelectGetsImplicitAliasResponse
{
	public int Count { get; set; }
}
