Declare @RunAsOf date = GetDate(); -------------- Optional Non-nullable Parameter
Declare @Sally table(Bob bit, Jim varchar(20), Sam int);
Declare @Bob1 varchar(10); ------------------- Required Non-nullable Parameter
Declare @Sally1 int;
Declare @Sally2 date;
Declare @Bob2 varchar(10) = Null; ------------ Optional Nullable Parameter
Declare @Bob3 varchar(10) = ''; -------------- Optional Non-nullable Parameter
Declare @EnvironmentName varchar(100) = 'Beta';
Declare @Debug bit = 1;

Insert Into @Sally Select 42;

Declare @Return int = Null;
Declare @ReturnThis int = 13;
Declare @Returns table(Bob int Null); ------------- First Returned Results As List of int?
--Declare @Return{_1}? int; -------------------- Second Returned Result As Scalar
Declare @Returns_Integer table(Bob int); ----- Third Returned Results As List of Integer Objects
											-- where Integer Objects have a property of Bob with a type of int
Declare @Returns2 table(Bob int, Sally bit); -- Fourth Returned Results As List of AutoGenerated Object
Declare @Return_That int;

Use [Database];

Insert Into @Returns2(Bob, Sally) Values (42, 1);
Insert Into @Returns2 Values (12, 0);

Select @ReturnThis