//HintName: Nested_output_reshapes_line_under_orderDataContext.g.cs
// <auto-generated />

#nullable enable

using Npgsql;
using NpgsqlTypes;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

using SQuiL;

namespace TestCase;

partial class Nested_output_reshapes_line_under_orderDataContext : PostgresDataContext
{
	public async Task<SQuiLResultType<Nested_output_reshapes_line_under_orderResponse>> ProcessNested_output_reshapes_line_under_orderAsync(
		Nested_output_reshapes_line_under_orderRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		Nested_output_reshapes_line_under_orderResponse response = new();
		
		var isOrder = false;
		var isLine = false;
		
		List<SQuiLError> errors = [];
		try
		{
			List<TestCase.Models.Order> __Order = [];
			List<TestCase.Models.Line> __Line = [];
			
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "orderid:int|customername:string":
					{
						isOrder = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexOrderID = reader.GetOrdinal("OrderID");
						var indexCustomerName = reader.GetOrdinal("CustomerName");
						
						do
						{
							var valueOrderID = reader.GetInt32(indexOrderID);
							var valueCustomerName = reader.GetString(indexCustomerName);
							
							__Order.Add(new(
								valueOrderID,
								valueCustomerName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "lineid:int|orderid:int|product:string|qty:int":
					{
						isLine = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexLineID = reader.GetOrdinal("LineID");
						var indexOrderID = reader.GetOrdinal("OrderID");
						var indexProduct = reader.GetOrdinal("Product");
						var indexQty = reader.GetOrdinal("Qty");
						
						do
						{
							var valueLineID = reader.GetInt32(indexLineID);
							var valueOrderID = reader.GetInt32(indexOrderID);
							var valueProduct = reader.GetString(indexProduct);
							var valueQty = reader.GetInt32(indexQty);
							
							__Line.Add(new(
								valueLineID,
								valueOrderID,
								valueProduct,
								valueQty));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
			
			foreach (var parent in __Order)
			{
				parent.Line = __Line.Where(c => c.OrderID == parent.OrderID).ToList();
			}
			
			response.Order = __Order;
		}
		catch(NpgsqlException e)
		{
			errors.Add(CreateError(e));
		}
		
		if (!isOrder) errors.Add(new(51001, 12, 1, 121, "Order", "Expected return table `Order`"));
		if (!isLine) errors.Add(new(51001, 12, 1, 122, "Line", "Expected return table `Line`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Drop Table If Exists Returns_Order;
		Create Temp Table Returns_Order (
			OrderID int Not Null Primary Key,
			CustomerName text Not Null);
		
		Drop Table If Exists Returns_Line;
		Create Temp Table Returns_Line (
			LineID int Not Null Primary Key,
			OrderID int Not Null,
			Product text Not Null,
			Qty int Not Null);
		
		
		
		Insert Into Returns_Order (OrderID, CustomerName) Values (1, 'Ada'), (2, 'Alan');
		Insert Into Returns_Line (LineID, OrderID, Product, Qty) Values (10, 1, 'Widget', 3), (11, 1, 'Gadget', 1), (12, 2, 'Gizmo', 5);
		Select OrderID, CustomerName From Returns_Order;
		Select LineID, OrderID, Product, Qty From Returns_Line;
		""";
	}
}
