//HintName: ManyToManyJunctionInputRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ManyToManyJunctionInputRequest
{
	public System.Collections.Generic.List<TestCase.Models.Student>? Student { get; set; } = [];
}
