//HintName: NotPrefixedColumnNamesDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;
using System.Data.Common;

using SQuiL;

namespace TestCase;

partial class NotPrefixedColumnNamesDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<NotPrefixedColumnNamesResponse>> ProcessNotPrefixedColumnNamesAsync(
		NotPrefixedColumnNamesRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@EnvironmentName", System.Data.SqlDbType.VarChar, EnvironmentName.Length, EnvironmentName),
			CreateParameter("@Debug", System.Data.SqlDbType.Bit, !request.DebugOnly && (request.Debug || EnvironmentName != "Production"))
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		NotPrefixedColumnNamesResponse response = new();
		
		var isRecords = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var tableTag = reader.GetName(0);
				if(tableTag.StartsWith("__SQuiL__Table__Type__"))
				{
					switch (tableTag)
					{
						case "__SQuiL__Table__Type__Error__":
						{
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							break;
						}
						case "__SQuiL__Table__Type__Returns_Records__":
						{
							isRecords = true;
							
							if (!await reader.ReadAsync(cancellationToken)) break;
							
							var indexRecordID = reader.GetOrdinal("RecordID");
							var indexNotes = reader.GetOrdinal("Notes");
							var indexNotEnrolled = reader.GetOrdinal("NotEnrolled");
							var indexNotification = reader.GetOrdinal("Notification");
							var indexNullableFlag = reader.GetOrdinal("NullableFlag");
							
							do
							{
								if (reader.GetString(0) == "Returns_Records")
								{
									var valueRecordID = reader.GetInt32(indexRecordID);
									var valueNotes = reader.GetString(indexNotes);
									var valueNotEnrolled = reader.GetBoolean(indexNotEnrolled);
									var valueNotification = reader.IsDBNull(indexNotification) ? default! : reader.GetString(indexNotification);
									var valueNullableFlag = reader.IsDBNull(indexNullableFlag) ? default! : reader.GetBoolean(indexNullableFlag);
									
									response.Records.Add(new(
										valueRecordID,
										valueNotes,
										valueNotEnrolled,
										valueNotification,
										valueNullableFlag));
								}
							}
							while (await reader.ReadAsync(cancellationToken));
							break;
						}
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isRecords) errors.Add(new(51001, 12, 1, 99, "Records", "Expected return table `Records`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Records table(
			[__SQuiL__Table__Type__Returns_Records__] varchar(max) default('Returns_Records'),
			[RecordID] int,
			[Notes] varchar(100),
			[NotEnrolled] bit,
			[Notification] varchar(100) Null,
			[NullableFlag] bit Null);
		
		Use [{builder.InitialCatalog}];
		
		Select 1;
		
		""";
	}
}
