//HintName: Records.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Records(
	int RecordID,
	string Notes,
	bool NotEnrolled,
	string? Notification,
	bool? NullableFlag);
