//HintName: NotPrefixedColumnNamesRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record NotPrefixedColumnNamesRequest
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
}
