//HintName: NotPrefixedColumnNamesResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record NotPrefixedColumnNamesResponse
{
	public System.Collections.Generic.List<RecordsTable>? Records { get; set; } = [];
}
