//HintName: DateFamilyVariableDefaultsDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class DateFamilyVariableDefaultsDataContext : SqlServerDataContext
{
	public async Task<SQuiLResultType> ProcessDateFamilyVariableDefaultsAsync(
		DateFamilyVariableDefaultsRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_OnDate", System.Data.SqlDbType.Date, request.OnDate),
			CreateParameter("@Param_AtTime", System.Data.SqlDbType.Time, request.AtTime),
			CreateParameter("@Param_StampedAt", System.Data.SqlDbType.DateTime, request.StampedAt),
			CreateParameter("@Param_CreatedAt", System.Data.SqlDbType.DateTimeOffset, request.CreatedAt)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		try
		{
			await command.ExecuteNonQueryAsync(cancellationToken);
			return SQuiLResultType.Success;
		}
		catch(SqlException e)
		{
			return new SQuiLResultType(CreateError(e));
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Use [{builder.InitialCatalog}];
		
		Select 1;
		""";
	}
}
