namespace Microsoft.CodeAnalysis;

public static class SourceGeneratorHelper
{
	public static string NamespaceName { get; } = "SQuiL";

	public static string ConfigRootPath { get; } = $"{NamespaceName}SolutionRoot";

	public static string AttributeName { get; } = $"{NamespaceName}Attribute";

	public static string AttributeFQDN { get; } = $"{NamespaceName}.{AttributeName}";

	public static string AttributeFile { get; } = $"{AttributeName}.g.cs";

	public static string BaseDataContextClassName { get; } = $"{NamespaceName}BaseDataContext";

	public static string DefaultConnectionStringAppSettingName { get; } = $"{NamespaceName}Database";

	public static string AutoGenerated { get; } = """
		// <auto-generated />
		
		""";

	public static string FileHeader { get; } = $"""
		{AutoGenerated}
		#nullable enable

		""";
}
