//HintName: ErrorAndErrorsAreNotInterchangeableRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ErrorAndErrorsAreNotInterchangeableRequest
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
}
