//HintName: Enabled_false_injects_no_transaction_wrapperRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Enabled_false_injects_no_transaction_wrapperRequest
{
	public System.Collections.Generic.List<TestCase.Models.Widget>? Widget { get; set; } = [];
}
