//HintName: Nested_input_reshapes_item_under_cartResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Nested_input_reshapes_item_under_cartResponse
{
	public System.Collections.Generic.List<TestCase.Models.CartLine>? CartLine { get; set; }
}
