//HintName: Nested_input_reshapes_item_under_cartDataContext.g.cs
// <auto-generated />

#nullable enable

using Npgsql;
using NpgsqlTypes;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class Nested_input_reshapes_item_under_cartDataContext : PostgresDataContext
{
	public async Task<SQuiLResultType<Nested_input_reshapes_item_under_cartResponse>> ProcessNested_input_reshapes_item_under_cartAsync(
		Nested_input_reshapes_item_under_cartRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		List<TestCase.Models.Cart> __Cart = [];
		List<TestCase.Models.Item> __Item = [];
		
		if (request.Cart is not null)
		{
			var cartKey = (int)(__Cart.Count + 1);
			__Cart.Add(new(
				cartKey,
				request.Cart.ShopperName));
			foreach (var item in request.Cart.Item ?? [])
			{
				var itemKey = (int)(__Item.Count + 1);
				__Item.Add(new(
					itemKey,
					cartKey,
					item.Product));
			}
		}
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		Nested_input_reshapes_item_under_cartResponse response = new();
		
		var isCartLine = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "shoppername:string|product:string":
					{
						isCartLine = true;
						
						response.CartLine ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexShopperName = reader.GetOrdinal("ShopperName");
						var indexProduct = reader.GetOrdinal("Product");
						
						do
						{
							var valueShopperName = reader.GetString(indexShopperName);
							var valueProduct = reader.GetString(indexProduct);
							
							response.CartLine.Add(new(
								valueShopperName,
								valueProduct));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(NpgsqlException e)
		{
			errors.Add(CreateError(e));
		}
		
		if (!isCartLine) errors.Add(new(51001, 12, 1, 102, "CartLine", "Expected return table `CartLine`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string inputCart(List<DbParameter> parameters)
		{
			AddJsonParameter(parameters, "@__json_Param_Cart", __Cart);
			
			return """
			Insert Into Param_Cart(CartID, ShopperName)
			Select x."CartID", x."ShopperName"
			From json_to_recordset(@__json_Param_Cart) AS x(
				"CartID" int,
				"ShopperName" text);
			""";
		}
		
		string inputItem(List<DbParameter> parameters)
		{
			AddJsonParameter(parameters, "@__json_Params_Item", __Item);
			
			return """
			Insert Into Params_Item(ItemID, CartID, Product)
			Select x."ItemID", x."CartID", x."Product"
			From json_to_recordset(@__json_Params_Item) AS x(
				"ItemID" int,
				"CartID" int,
				"Product" text);
			""";
		}
		
		string Query(List<DbParameter> parameters) => $"""
		Drop Table If Exists Param_Cart;
		Create Temp Table Param_Cart (
			CartID int Not Null Primary Key,
			ShopperName text Not Null);
		{inputCart(parameters)}
		
		Drop Table If Exists Params_Item;
		Create Temp Table Params_Item (
			ItemID int Not Null Primary Key,
			CartID int Not Null,
			Product text Not Null);
		{inputItem(parameters)}
		
		Drop Table If Exists Returns_CartLine;
		Create Temp Table Returns_CartLine (
			ShopperName text Not Null,
			Product text Not Null);
		
		
		
		Insert Into Returns_CartLine (ShopperName, Product) Select c.ShopperName, i.Product From Param_Cart c Join Params_Item i On i.CartID = c.CartID;
		Select ShopperName, Product From Returns_CartLine;
		""";
	}
}
