//HintName: Cart.g.cs
// <auto-generated />

#nullable enable

namespace TestCase.Models;

public partial record Cart(
	int CartID,
	string ShopperName)
{
	public System.Collections.Generic.List<TestCase.Models.Item>? Item { get; set; } = [];
}
