//HintName: PositionalDebugRollbackFalse_AlwaysCommitsRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record PositionalDebugRollbackFalse_AlwaysCommitsRequest
{
	public bool Debug { get; set; }
}
