//HintName: TestCase.PositionalDebugRollbackFalse_AlwaysCommitsDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class PositionalDebugRollbackFalse_AlwaysCommitsDataContext : SQuiLBaseDataContext
{
    public PositionalDebugRollbackFalse_AlwaysCommitsDataContext(IConfiguration Configuration) : base(Configuration) { }
}
