//HintName: PositionalDebugRollbackFalse_AlwaysCommitsResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record PositionalDebugRollbackFalse_AlwaysCommitsResponse
{
	public int Count { get; set; }
}
