//HintName: TestCase.EnabledTransactionWrapsReaderPathDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class EnabledTransactionWrapsReaderPathDataContext : SQuiLBaseDataContext
{
    public EnabledTransactionWrapsReaderPathDataContext(IConfiguration Configuration) : base(Configuration) { }
}
