//HintName: EnabledTransactionWrapsReaderPathResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record EnabledTransactionWrapsReaderPathResponse
{
	public int Count { get; set; }
}
