//HintName: RowsTable.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record RowsTable(
	int RowID,
	int Qty)
{
	public decimal Amount { get; init; } = 1.5m;
	public string Note { get; init; } = "hello";
}
