//HintName: ColumnDefaultBeforeRequiredRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ColumnDefaultBeforeRequiredRequest
{
	public System.Collections.Generic.List<RowsTable> Rows { get; set; } = [];
}
