//HintName: IdenticalOutputSignaturesCollideSP0030DataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class IdenticalOutputSignaturesCollideSP0030DataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<IdenticalOutputSignaturesCollideSP0030Response>> ProcessIdenticalOutputSignaturesCollideSP0030Async(
		IdenticalOutputSignaturesCollideSP0030Request request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		IdenticalOutputSignaturesCollideSP0030Response response = new();
		
		var isActive = false;
		var isInactive = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "personid:int|name:string":
					{
						isActive = true;
						
						response.Active ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexPersonID = reader.GetOrdinal("PersonID");
						var indexName = reader.GetOrdinal("Name");
						
						do
						{
							var valuePersonID = reader.GetInt32(indexPersonID);
							var valueName = reader.GetString(indexName);
							
							response.Active.Add(new(
								valuePersonID,
								valueName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
					case "personid:int|name:string":
					{
						isInactive = true;
						
						response.Inactive ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexPersonID = reader.GetOrdinal("PersonID");
						var indexName = reader.GetOrdinal("Name");
						
						do
						{
							var valuePersonID = reader.GetInt32(indexPersonID);
							var valueName = reader.GetString(indexName);
							
							response.Inactive.Add(new(
								valuePersonID,
								valueName));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isActive) errors.Add(new(51001, 12, 1, 105, "Active", "Expected return table `Active`"));
		if (!isInactive) errors.Add(new(51001, 12, 1, 106, "Inactive", "Expected return table `Inactive`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Active table(
			[PersonID] int,
			[Name] varchar(100));
		
		Declare @Returns_Inactive table(
			[PersonID] int,
			[Name] varchar(100));
		
		Use [{builder.InitialCatalog}];
		
		Select * From @Returns_Active;
		Select * From @Returns_Inactive;
		""";
	}
}
