//HintName: CoursesTable.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record CoursesTable(
	string EvalationID,
	string TermCode,
	string CourseCode,
	string CourseTitle,
	string ProfessorPicture,
	string ProfessorName,
	string EvaluationState,
	string EvaluationStatus);
