//HintName: Participation.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data.Models;

public partial record Participation(
	string SectionID,
	string PersonID,
	string ProfessorID,
	string TermCode,
	System.DateTime CompletedDate);
