//HintName: Overrides.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data.Models;

public partial record Overrides(
	string SectionID,
	string TermCode,
	string CourseCode,
	System.DateTime BeginDate,
	System.DateTime EndDate);
