//HintName: GetActiveTermsForStudentEvaluationsDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace CourseEvaluation.Application.Data;

partial class CourseEvaluationDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<GetActiveTermsForStudentEvaluationsResponse>> ProcessGetActiveTermsForStudentEvaluationsAsync(
		GetActiveTermsForStudentEvaluationsRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("Warehouse");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_AsOfDate", System.Data.SqlDbType.Date, request.AsOfDate ?? (object)System.DBNull.Value
			, p => p.IsNullable = true)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		GetActiveTermsForStudentEvaluationsResponse response = new();
		
		var isTerms = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "termcode:string":
					{
						isTerms = true;
						
						response.Terms ??= [];
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						var indexTermCode = reader.GetOrdinal("TermCode");
						
						do
						{
							var valueTermCode = reader.GetString(indexTermCode);
							
							response.Terms.Add(new(
								valueTermCode));
						}
						while (await reader.ReadAsync(cancellationToken));
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isTerms) errors.Add(new(51001, 12, 1, 81, "Terms", "Expected return table `Terms`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Returns_Terms table(
			[TermCode] varchar(10));
		
		Use [{builder.InitialCatalog}];
		
		If @Param_AsOfDate Is Null Set @Param_AsOfDate = GetDate();
		
		Insert Into @Returns_Terms
		Select		t.Term
		From		pub.Terms t
		Where		@Param_AsOfDate Between t.RegStartDate And IsNull(t.GradesDueDate, DateAdd(week, 1, t.EndDate))
		
		Select * From @Returns_Terms;
		""";
	}
}
