//HintName: GetQuestionsForEvaluationRequest.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetQuestionsForEvaluationRequest
{
	public bool Debug { get; set; } = true;
	
	public SectionTable? Section { get; set; } = default!;
}
