//HintName: GetActiveTermsForStudentEvaluationsResponse.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetActiveTermsForStudentEvaluationsResponse
{
	public System.Collections.Generic.List<TermTable> Terms { get; set; } = [];
}
