//HintName: GetCourseForEvaluationByEvaluationIDResponse.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetCourseForEvaluationByEvaluationIDResponse
{
	public string SectionID { get; set; } = "";
	
	public string PersonID { get; set; } = "";
	
	public string TermCode { get; set; } = "";
}
