//HintName: GetStudentCoursesForEvaluationByTermRequest.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetStudentCoursesForEvaluationByTermRequest
{
	public bool Debug { get; set; }
	
	public string? PersonID { get; set; }
	
	public string? CourseCode { get; set; }
	
	public System.DateOnly? AsOfDate { get; set; }
	
	public System.Collections.Generic.List<TermTable> Terms { get; set; } = [];
	
	public System.Collections.Generic.List<ParticipationTable> Participation { get; set; } = [];
	
	public System.Collections.Generic.List<OverridesTable> Overrides { get; set; } = [];
}
