//HintName: GetQuestionsForEvaluationResponse.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetQuestionsForEvaluationResponse
{
	public System.Collections.Generic.List<Questions>? Questions { get; set; }
}
