//HintName: GetCourseForEvaluationByEvaluationIDRequest.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetCourseForEvaluationByEvaluationIDRequest
{
	public bool Debug { get; set; }
	
	public string? EvaluationID { get; set; }
}
