//HintName: GetSectionDetailsRequest.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetSectionDetailsRequest
{
	public bool Debug { get; set; }
	
	public string? SectionID { get; set; }
}
