//HintName: GetStudentCoursesForEvaluationByTermResponse.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetStudentCoursesForEvaluationByTermResponse
{
	public System.Collections.Generic.List<CoursesTable> Courses { get; set; } = [];
}
