//HintName: GetStudentParticipationAndSectionOverridesRequest.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetStudentParticipationAndSectionOverridesRequest
{
	public bool Debug { get; set; }
	
	public string? PersonID { get; set; }
	
	public System.Collections.Generic.List<TermTable> Terms { get; set; } = [];
}
