//HintName: GetActiveTermsForStudentEvaluationsRequest.g.cs
// <auto-generated />

#nullable enable

namespace CourseEvaluation.Application.Data;

public partial record GetActiveTermsForStudentEvaluationsRequest
{
	public bool Debug { get; set; }
	
	public System.DateOnly? AsOfDate { get; set; }
}
