//HintName: DateTimeOffsetVariableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DateTimeOffsetVariableResponse
{
	public System.DateTimeOffset ModifiedAt { get; set; }
}
