//HintName: DebugRollbackFalseAlwaysCommitsRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DebugRollbackFalseAlwaysCommitsRequest
{
	public bool Debug { get; set; }
}
