//HintName: DebugRollbackFalseAlwaysCommitsResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record DebugRollbackFalseAlwaysCommitsResponse
{
	public int Count { get; set; }
}
