//HintName: TestCase.DebugRollbackFalseAlwaysCommitsDataContext.Constructor.g.cs
// <auto-generated />

#nullable enable
using Microsoft.Extensions.Configuration;

using SQuiL;

namespace TestCase;

partial class DebugRollbackFalseAlwaysCommitsDataContext : SQuiLBaseDataContext
{
    public DebugRollbackFalseAlwaysCommitsDataContext(IConfiguration Configuration) : base(Configuration) { }
}
