//HintName: EmbeddedLookupNullableKeyResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record EmbeddedLookupNullableKeyResponse
{
	public System.Collections.Generic.List<TestCase.Models.Structure>? Structure { get; set; }
}
