//HintName: Input2VariableRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Input2VariableRequest
{
	public bool Debug { get; set; }
	public bool DebugOnly { get; set; }
	
	public ObjectObject? Object { get; set; } = default!;
}
