//HintName: Input2VariableRequest.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record Input2VariableRequest
{
	public ObjectObject? Object { get; set; } = default!;
}
