//HintName: ScalarNullInitializerIsNullableDataContext.g.cs
// <auto-generated />

#nullable enable

using Microsoft.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

using SQuiL;

namespace TestCase;

partial class ScalarNullInitializerIsNullableDataContext : SQuiLBaseDataContext
{
	public async Task<SQuiLResultType<ScalarNullInitializerIsNullableResponse>> ProcessScalarNullInitializerIsNullableAsync(
		ScalarNullInitializerIsNullableRequest request,
		CancellationToken cancellationToken = default!)
	{
		var builder = ConnectionStringBuilder("SQuiLDatabase");
		using var connection = CreateConnection(builder.ConnectionString);
		
		var command = connection.CreateCommand();
		
		List<DbParameter> parameters = new()
		{
			CreateParameter("@Param_Required", System.Data.SqlDbType.Int, request.Required),
			CreateParameter("@Param_Nullable", System.Data.SqlDbType.Int, request.Nullable ?? (object)System.DBNull.Value
			, p => p.IsNullable = true),
			CreateParameter("@Param_Name", System.Data.SqlDbType.VarChar, 50, request.Name switch
			{
				null => (object)System.DBNull.Value,
				{ Length: <= 50 } => request.Name,
				_ => throw new Exception(
					"Request model data is larger then database size for the property [Name].")
			}, p => p.IsNullable = true),
			CreateParameter("@Param_Defaulted", System.Data.SqlDbType.Int, request.Defaulted)
		};
		
		command.CommandText = Query(parameters);
		command.Parameters.AddRange(parameters.ToArray());
		
		await connection.OpenAsync(cancellationToken);
		
		ScalarNullInitializerIsNullableResponse response = new();
		
		var isCount = false;
		
		List<SQuiLError> errors = [];
		try
		{
			using var reader = await command.ExecuteReaderAsync(cancellationToken);
			
			do
			{
				var __shape = ShapeKey(reader);
				switch (__shape)
				{
					case "count:int":
					{
						if (isCount) throw new Exception(
							"Already returned value for `Count`");
						
						isCount = true;
						
						if (!await reader.ReadAsync(cancellationToken)) break;
						
						response.Count = !reader.IsDBNull(0) ? reader.GetInt32(0) : throw new NullReferenceException("Return value for Count cannot be null.");
						break;
					}
				}
			}
			while (await reader.NextResultAsync(cancellationToken));
		}
		catch(SqlException e)
		{
			errors.Add(new(e.Number, 11, e.State, e.LineNumber, e.Procedure, e.Message));
		}
		
		if (!isCount) errors.Add(new(51001, 12, 1, 83, "Count", "Expected return scaler `Count`"));
		
		if(errors.Count == 0)
			return new(response);
		
		return new(errors);
		
		string Query(List<DbParameter> parameters) => $"""
		Declare @Return_Count int;
		
		Use [{builder.InitialCatalog}];
		
		Select @Return_Count = 1;
		""";
	}
}
