//HintName: ScalarNullInitializerIsNullableResponse.g.cs
// <auto-generated />

#nullable enable

namespace TestCase;

public partial record ScalarNullInitializerIsNullableResponse
{
	public int Count { get; set; }
}
